; - Lines that start with ; or # are comments and are ignored by the app
ParentProfile = MMOGO_AOA_Default

###############################################################################
## Set these with your actual in-game keybinds, and add any keys you
## have changed from game defaults here with the key you have assigned.
## See the _Base.ini file for the names of key binds you can assign
###############################################################################

[KeyBinds]
StrafeLeft = Q
StrafeRight = E
TurnRight = D
TurnLeft = A
AutoRun = NumLock
; Using hotbuttons instead of chat box macros can improve responsiveness
; This can be dragged from Abilities->Social to a Hotbutton# then assigned here
WhoTarget = /whotarget
; Set this to "Camp = Hotbutton10" to use its default hotbutton assignment
Camp = /camp


###############################################################################
## Make sure this is a position of the screen that will NEVER have any UI
## elements (windows) covering it (usually a corner works best).
## Can't be fully in a corner though or mouselook won't initiate when moving
## toward the edge - needs room to initially move mouse to activate mouselook!
###############################################################################

[Hotspots]
MouseLookStart = R-32, T+32


###############################################################################
## These categories are often updated by the control scheme automatically when
## set settings or use the layout editor.
###############################################################################

[Variables]

[Hotspots]

[System]


###############################################################################
## NOTE:
## Remember you can also change the macros in the Macros menu at runtime
## by holding a direction on the D-Pad while in the Macros (tap L2) menu.
###############################################################################
