ParentProfile = MnM_Default

# For a breakdown of the base controls, read the generated _Default.ini file! #
; - Lines that start with ; or # are comments and are ignored by the app

###############################################################################
## Set these with your actual in-game keybinds, and add any keys you
## have changed from game defaults here with the key you have assigned.
## See the _Base.ini file for the names of key binds you can assign
###############################################################################

[KeyBinds]
# Adding Strafe keybinds is optional, but doing so will improve responsiveness
# of movement controls. BE SURE TO ASSIGN THESE IN-GAME TO THE SAME THING!
StrafeLeft =
StrafeRight =


###############################################################################
## For better responsiveness, common macros should be put on your hotbar and
## triggered that way instead of having the app type them in to the chat box.
## This will improve controls responsiveness since movement and other controls
## will halt briefly while the chat box is being used!
## Example setup (for /whotarget):
##    Use /macros and make a /whotarget macro
##    Add the macro to Hotbutton 12 in your Hotbar in-game
##    Replace below line "WhoTarget = /whot" with "WhoTarget = Hotbutton12"
###############################################################################

# This will be used when you press L2+R2 and can be set to whatever you want,
# but the intent is to have it trigger Sense Heading on your hotbar.
Heading =

; WhoTarget is used every time switch player targets using L2+R1
WhoTarget = /whotarget

; DragCorpse will be spammed using Corpse Drag Mode and is highly recommended
; to move to a hotbar macro to avoid it interfering with moving while dragging
DragCorpse = /corpse

; These can be used via the L2 Macro menu or in Corpse Drag Mode, but not very
; often, so it might be fine to just leave them being typed in manually
TargetNearestCorpse = /tar corpse
LootTarget = /loot
AutoFollow = /follow


###############################################################################
## Default control scheme has nothing set for the Select/Back/Share button,
## since in EQOA it changed camera view - which this game has no key bind for.
## Set it to do whatever you like here!
###############################################################################

[Scheme]
Tap Select = Screenshot
Hold Select = ToggleUI

[Layer.L2Held]
Tap Select = GameStats
Hold Select = ToggleMusic


###############################################################################
## Make sure this is a position of the screen that will NEVER have any UI
## elements (windows) covering it (usually a corner works best)
###############################################################################

[Hotspots]
MouseLookStart = L, T


###############################################################################
## These categories are often updated by the control scheme automatically when
## set settings or use the layout editor.
###############################################################################

[Variables]

[Hotspots]

[System]


###############################################################################
## NOTE:
## Remember you can also change the macros in the Macros menu at runtime
## by holding a direction on the D-Pad while in the Macros (tap L2) menu.
###############################################################################
