; - Lines that start with ; or # are comments and are ignored by the app
ParentProfile = MMOGO_MnM_Default

###############################################################################
## Set these with your actual in-game keybinds, and add any keys you
## have changed from game defaults here with the key you have assigned.
## See the _Base.ini file for the names of key binds you can assign
###############################################################################

[KeyBinds]
; Adding Strafe keybinds is optional, but doing so will improve responsiveness
; of movement controls. If you do add keys below though, be certain the in-game
; binds are set to the same keys or strafing won't work at all!
StrafeLeft =
StrafeRight =
; If you want to use multiple hotbar banks, it is recommended you un-comment the
; below lines and remap the in-game keybinds to match (or choose different keys
; entirely), because the default shift+numpad# keys don't work reliably.
;HotBank0 = Num0
;HotBank1 = Num1
;HotBank2 = Num2
;HotBank3 = Num3
;HotBank4 = Num4
;HotBank5 = Num5
;HotBank6 = Num6
;HotBank7 = Num7
;HotBank8 = Num8
;HotBank9 = Num9


###############################################################################
## For better responsiveness, some of the below common macro commands may be
## better off triggering a macro on your hotbar instead of the app pasting it
## in to your chat box every time, which locks up other controls briefly.
## Copy the command to an in-game macro, add said macro to your hotbar, and
## then replace the /command below with "Hotbar1" or "HotBar12" etc. to match.
###############################################################################

; WhoTarget is used whenever target players with L2+R1 so is an especially good
; candidate to move to a hotbar macro to avoid movement pauses while targeting
WhoTarget = /whotarget
AutoFollow = /follow
LootTarget = /loot
LootNearestCorpse = /tar corpse \n /loot
; Should set this to at least "/tar CharName's corpse\n/loot" even if don't set
; it as a hotbar macro, so it will only target and loot your own corpse
LootOwnCorpse = /tar corpse \n /loot


###############################################################################
## Make sure this is a position of the screen that will NEVER have any UI
## elements (windows) covering it (usually a corner works best)
###############################################################################

[Hotspots]
MouseLookStart = L, T


###############################################################################
## Default control scheme has nothing set for the Select/Back/Share button,
## since in EQOA it changed camera view - which this game has no key bind for.
## Set it to do whatever you like here!
###############################################################################

[Scheme]
Tap Select = Screenshot
Hold Select = ToggleUI

[Layer.L2Held]
Tap Select = GameStats
Hold Select = ToggleMusic


###############################################################################
## NOTE:
## Remember you can also change the macros in the Macros menu during play
## by holding a direction on the D-Pad while in the Macros (tap L2) menu.
###############################################################################

; Below may be updated by app directly when set settings or use editor
[Variables]

[Hotspots]

[System]
