; - Lines that start with ; or # are comments and are ignored by the app
ParentProfile = MMOGO_MnM_Default

###############################################################################
## Set these with your actual in-game keybinds, and add any keys you
## have changed from game defaults here with the key you have assigned.
## See the _Base.ini file for the names of key binds you can assign
###############################################################################

[KeyBinds]
; Adding Strafe keybinds is optional, but doing so will improve responsiveness
; of movement controls. If you do add keys below though, be certain the in-game
; binds are set to the same keys or strafing won't work at all!
StrafeLeft =
StrafeRight =


###############################################################################
## For better responsiveness, some of the below common macro commands may be
## better off triggering a macro on your hotbar instead of the app pasting it
## in to your chat box every time, which locks up other controls briefly.
## Copy the command to an in-game macro, add said macro to your hotbar, and
## then replace the /command below with "Hotbar1" or "HotBar12" etc. to match.
###############################################################################

; WhoTarget is used whenever target players with L2+R1 so is an especially good
; candidate to move to a hotbar macro to avoid movement pauses while targeting
WhoTarget = /whotarget
AutoFollow = /follow
LootTarget = /loot
LootNearestCorpse = /tar corpse \n /loot
; Should set this to at least "/tar CharName's corpse\n/loot" even if don't set
; it as a hotbar macro, so it will only target and loot your own corpse
LootOwnCorpse = /tar corpse \n /loot


###############################################################################
## Make sure this is a position of the screen that will NEVER have any UI
## elements (windows) covering it (usually a corner works best)
###############################################################################

[Hotspots]
MouseLookStart = L, T


###############################################################################
## Default control scheme has nothing set for the Select/Back/Share button,
## since in EQOA it changed camera view - which this game has no key bind for.
## Set it to do whatever you like here!
###############################################################################

[Scheme]
; F12 takes screenshots - makes sense for the "share" button I guess
Select = F12

[Layer.L2Held]
; This will toggle the meter that displays FPS and ping time
Select = GameStats


###############################################################################
## NOTE:
## Remember you can also change the macros in the Macros menu during play
## by holding a direction on the D-Pad while in the Macros (tap L2) menu.
###############################################################################

; Below may be updated by app directly when set settings or use editor
[Variables]

[Hotspots]

[System]
