# - Lines that start with # are comments and are ignored by the application
ParentProfile = MMOGO_P99_Default

###############################################################################
## Set these with your actual in-game keybinds, and add any keys you
## have changed from game defaults here with the key you have assigned
## See the _Base.ini file for the names of key binds you can assign
###############################################################################

[KeyBinds]
OpenBags =
CloseBags =
TargetLast =
; These are set just so *something* happens when using R1 to target, since by
; default TargetCyclePC/NPC aren't mapped to anything. Be sure to bind them
; and set these to match your binds, or they'll just target "nearest" instead!
;TargetCyclePC = F7
;TargetCycleNPC = F8
; Adding Strafe keybinds is optional, but doing so will improve responsiveness
; of movement controls. If you do add keys below though, be certain the in-game
; binds are set to the same keys or strafing won't work at all!
StrafeLeft =
StrafeRight =
; Probably should be "PasteText = Ctrl-V" but you still have to bind it in-game!
; Binding this and setting it will SIGNIFICANTLY speed up text macro usage!
PasteText =


###############################################################################
## For better responsiveness, some of the below common macro commands may be
## better off triggering a macro on your hotbar instead of the app typing it
## in to your chat box every time, which locks up other controls briefly.
## Copy the command to an in-game macro, add said macro to your hotbar, and
## then replace the /command below with things like "HotPage2, HotButton4" etc.
###############################################################################

[KeyBinds]
Assist = /assist
WhoTarget = /whot
LootTarget = /loot
LootNearestCorpse = /tar a \n /loot
; Suggested set this to /tar CHARNAME's corpse
LootOwnCorpse = /loot
; Suggested /loc+/autoinventory+/doability 6 (set to Sense Heading) for this
Heading = /loc


###############################################################################
## Make sure this is a position of the screen that will NEVER have any UI
## elements (windows) covering it (usually a corner works best)
###############################################################################

[Hotspots]
MouseLookStart = R, B


###############################################################################
## If you have a hard time reading the yellow text on grey/tan BG that EQ uses
## when applied to the overlay buttons, try this alternate color scheme.
###############################################################################

[Appearance]
;SelectedBorderRGB = 230, 126, 34
;SelectedLabelRGB = 0, 0, 0


###############################################################################
## NOTES:
## To see how I personally use a controller with EverQuest Project 1999,
## consider using the customized profile and associated UI files found at
## https://github.com/OneCrazyCoder/MMOGamepadOverlay/releases/tag/UIFilePacks
## in the file "TaronP99UIFiles.zip", and play the game at 720p resolution.
##
## Remember you can also change the macros in the Macros menu at runtime
## by holding a direction on the D-Pad while in the Macros (tap L2) menu.
##
## You may want to also reassign many of the macros in the Macros menu
## to use in-game socials put in your hotbar instead of chat box strings!
###############################################################################

; Below may be updated by app directly when set settings or use editor
[Variables]

[Hotspots]

[System]
; Set this to yes if you generally always play in full-screen mode anyway
StartInFullScreenWindow = No
