//------------------------------------------------------------------------------
//	Originally written by Taron Millet, except where otherwise noted
//------------------------------------------------------------------------------

#include "Profile.h"

#include "Dialogs.h"
#include "TargetApp.h"

#include "Resources/resource.h"

#include <fstream>

namespace Profile
{

#if _DEBUG
// Having this defined silently re-creates all generated INI files every launch,
// so they always reflect any changes made to resource versions.
#define ALWAYS_REFRESH_DEFAULT_INI
#endif

//------------------------------------------------------------------------------
// Const Data
//------------------------------------------------------------------------------

enum {
kINIFileBufferSize = 4096, // How many chars to process at a time from .ini
kVarsSectionIdx = 0,
kUIScaleVarID = 0,
kWidthVarID = 1,
kHeightVarID = 2,
};

const char* kProfileFileNamePrefix = "MMOGO_";
const char* kProfileFileNameSuffix = ".ini";
const char* kProfileKeyPrefix = "Profile";
const char* kBaseGameSettingsSection = "System";
const char* kAutoLaunchAppKey = "AutoLaunchApp";
const char* kAutoLaunchAppParamsKey = "AutoLaunchAppParams";
const char* kAutoQuitWithAppKey = "QuitWhenAutoLaunchAppDoes";
const char* kAutoQuitWithWindowKey = "QuitWhenTargetWindowCloses";
const char* kMainWindowNameKey = "WindowName";
const char* kKnownIssuesKey = "KnownIssues";
const char* kAutoLoadProfileKey = "AutoLoadProfile";
const char* kAutoGenVersionKey = "AutoGeneratedVersion";
const char* kVariablesSectionName = "Variables";
const char* kUIScaleVarName = "UIScale";
const char* kWidthVarName = "W";
const char* kHeightVarName = "H";
const char* kLinuxVarName = "Linux";
const char* kCopyIconsVarName = "CopyIconsEnabled";
const char* kCopyExcludeOverlaysVarName = "CopyOverlappedIcons";
const std::string kEndOfLine = "\r\n";

struct ResourceFile
{
	const char* dispName;
	const char* fileName;
	WORD resID;
	int version;
};

const ResourceFile kResTemplateCore =
	{	"Core",				"Core",				IDR_TEXT_INI_CORE,		24	};

const ResourceFile kResTemplateBase[] =
{//		dispName			fileName			resID					ver
	{	"AOA Base",			"AOA Base",			IDR_TEXT_INI_BASE_AOA,	23	},
	{	"EQ P99 Base",		"P99 Base",			IDR_TEXT_INI_BASE_P99,	22	},
	{	"EQ PQ Base",		"PQ Base",			IDR_TEXT_INI_BASE_PQ,	21	},
	{	"M&M Base",			"MnM Base",			IDR_TEXT_INI_BASE_MNM,	24	},
};

const ResourceFile kResTemplateDefault[] =
{//		dispName			fileName			resID					ver
	{	"AOA Default",		"AOA Default",		IDR_TEXT_INI_DEF_AOA,	20	},
	{	"EQ P99 Default",	"P99 Default",		IDR_TEXT_INI_DEF_P99,	22	},
	{	"EQ PQ Default",	"PQ Default",		IDR_TEXT_INI_DEF_PQ,	21	},
	{	"M&M Default",		"MnM Default",		IDR_TEXT_INI_DEF_MNM,	25	},
};

const ResourceFile kResTemplateCustom[] =
{//		dispName						fileName	resID					ver
	{	"Adrullan Online Adventures",	"AOA",		IDR_TEXT_INI_CUST_AOA,	0 },
	{	"EverQuest: Project 1999",		"P99",		IDR_TEXT_INI_CUST_P99,	0 },
	{	"EverQuest: Project Quarm",		"PQ",		IDR_TEXT_INI_CUST_PQ,	0 },
	{	"Monsters & Memories",			"MnM",		IDR_TEXT_INI_CUST_MNM,	0 },
};

const ResourceFile kResTemplateBlank = { "", "", IDR_TEXT_INI_CUST_BLANK, 0 };

enum EParseMode
{
	eParseMode_Header,
	eParseMode_Sections,
	eParseMode_Full,
};

struct ZERO_INIT(ProfileData)
{
	std::string path;
	std::string parent;
	bool isAParent;
};

typedef void (*ParseINICallback)(
	const std::string& theSection,
	const std::string& theName,
	const std::string& theValue,
	void* theUserData);

struct ZERO_INIT(UnsavedProperty)
{
	int sectionID;
	int propertyID;
	std::string value;
};

struct ZERO_INIT(VarPropDependency)
{
	u32 varID : 9;
	u32 sectID : 9;
	u32 propID : 14;

	u32 cmpVal() const { return (varID << 23) | (sectID << 14) | propID; }
	bool operator<(const VarPropDependency& rhs) const
	{ return cmpVal() < rhs.cmpVal(); }
	bool operator==(const VarPropDependency& rhs) const
	{ return cmpVal() == rhs.cmpVal(); }
};

struct BaseGameSettings
{
	std::string autoLaunchAppPath;
	std::string autoLaunchAppParams;
	std::string autoQuitWithTargetApp;
	std::string autoQuitWithTargetWin;
	std::string mainWindowName;
	std::string knownIssuesList;
};


//------------------------------------------------------------------------------
// Static Variables
//------------------------------------------------------------------------------

static SectionsMap sSectionsMap;
static SectionsMap sChangedSectionsMap;
static StringToValueMap<ProfileData> sProfiles;
static std::vector<std::string> sDisplayedProfileList;
static std::vector<UnsavedProperty> sUnsavedChangesList;
static std::vector<VarPropDependency> sVarPropDepList;
static std::string sKnownIssuesRTF;
static int sAutoLoadProfileIdx = 0; // = core, which is invalid for auto-load
static int sLoadedProfileIdx = 0; // = core, which is invalid to directly load
static int sNewBaseProfileIdx = -1;
static bool sPerformedProfileFolderScan = false;
static bool sNeedShowKnownIssues = false;


//------------------------------------------------------------------------------
// Debugging
//------------------------------------------------------------------------------

#ifndef NDEBUG
static int sPropertyMapPtrCount = 0;
PropertyMapPtr::PropertyMapPtr(const PropertyMap* ptr)
: ptr(ptr) { ++sPropertyMapPtrCount; }
PropertyMapPtr::PropertyMapPtr(const PropertyMapPtr& rhs)
: ptr(rhs.ptr) { ++sPropertyMapPtrCount; }
PropertyMapPtr::~PropertyMapPtr()
{ --sPropertyMapPtrCount; }
PropertyMapPtr& PropertyMapPtr::operator=(const PropertyMapPtr& rhs)
{ ptr = rhs.ptr; return *this; }
const PropertyMap* PropertyMapPtr::operator->() const { return ptr; }
const PropertyMap& PropertyMapPtr::operator*() const { return *ptr; }
PropertyMapPtr::operator const PropertyMap*() const { return ptr; }
inline static void confirmSafeToWriteToMap()
{ DBG_ASSERT(sPropertyMapPtrCount == 0); }
#else
inline static void confirmSafeToWriteToMap() {}
#endif


//------------------------------------------------------------------------------
// Local Functions
//------------------------------------------------------------------------------

static const std::string& iniFolderPath()
{
	static std::string sFolderPath;
	if( sFolderPath.empty() )
	{
		// Just use our application folder (for now)
		sFolderPath = getAppFolder();

		// Make sure it actually exists
		// (obviously it has to, but leaving this here for possibly
		// later changing the .ini folder to AppData or something)
		size_t aCurPos = 0;
		for(;;)
		{
			size_t aSlashPos = sFolderPath.find_first_of("\\/", aCurPos);
			if( aSlashPos == std::string::npos )
			{
				_wmkdir(widen(sFolderPath).c_str());
				break;
			}

			aCurPos = aSlashPos + 1;

			std::string aCurPath = sFolderPath.substr(0, aSlashPos);
			_wmkdir(widen(aCurPath).c_str());
		}
	}

	return sFolderPath;
}


static std::string extractProfileName(const std::string& theString)
{
	std::string result = removeExtension(getFileName(theString));
	const std::string& prefix = upper(kProfileFileNamePrefix);
	if( upper(result).compare(0, prefix.length(), upper(prefix)) == 0 )
		result = result.substr(prefix.length());
	return replaceChar(result, '_', ' ');
}


static std::string profileNameToFilePath(
	const std::string& theName, bool replaceSpaces = true)
{
	DBG_ASSERT(theName == extractProfileName(theName));
	std::string result = iniFolderPath();
	result += kProfileFileNamePrefix;
	if( replaceSpaces )
		result += replaceChar(theName, ' ', '_');
	else
		result += theName;
	result += kProfileFileNameSuffix;
	return result;
}


static inline bool fileExists(const std::string& theFilePath)
{
	return isValidFilePath(theFilePath);
}


static void parseINI(
	ParseINICallback theCallbackFunc,
	const std::string& theFilePath,
	EParseMode theParseMode,
	void* theUserData = NULL)
{
	std::ifstream aFile(widen(theFilePath).c_str(), std::ios::binary);
	if( !aFile.is_open() )
	{
		logFatalError("Could not open file %s", theFilePath.c_str());
		return;
	}

	// Prepare input buffer
	// +1 on size is to accommodate an extra newline character when
	// reach end of file
	char aBuffer[kINIFileBufferSize+1];
	std::streamsize aBufferSize = kINIFileBufferSize;
	std::string aNewSection;
	std::string aSection;
	std::string aKey;
	std::string aValue;

	enum
	{
		ePIState_Whitespace,
		ePIState_Section,
		ePIState_Key,
		ePIState_Value,
		ePIState_Comment,
	} aState = ePIState_Whitespace;

	while(aFile.good())
	{
		// Read next chunk from file
		aFile.read(aBuffer, aBufferSize);
		if( aFile.eof() || aFile.gcount() < aBufferSize )
		{// Put eol at end of file in case there wasn't one already
			aBufferSize = aFile.gcount() + 1;
			aBuffer[aBufferSize-1] = '\n';
			DBG_ASSERT(aBufferSize <= ARRAYSIZE(aBuffer));
		}
		else if( aFile.bad() )
		{
			logFatalError("Unknown error reading %s", theFilePath.c_str());
			aFile.close();
			return;
		}

		for(int i = 0; i < aBufferSize; ++i)
		{// Step through buffer character-by-character
			const char c = aBuffer[i];
			switch(aState)
			{
			case ePIState_Whitespace:
				// Look for a section, key, or comment
				if( c == '[' )
				{
					if( theParseMode == eParseMode_Header )
					{// Stop parsing once hit [ in this mode
						aFile.close();
						return;
					}
					aState = ePIState_Section;
					aNewSection.clear();
				}
				else if( c == '#' || c == ';' )
				{
					aState = ePIState_Comment;
				}
				else if( u8(c) > ' ' )
				{
					if( theParseMode == eParseMode_Sections &&
						aSection.empty() )
					{// Treat anything before first section as a comment
						aState = ePIState_Comment;
					}
					else
					{
						aState = ePIState_Key;
						aKey.clear();
						aKey.push_back(c);
					}
				}
				break;

			case ePIState_Section:
				// Look for end of line after ']' to end section
				switch(c)
				{
				case '\r': case '\n': case '\0':
					aNewSection = trim(aNewSection);
					if( aNewSection.size() > 1 &&
						aNewSection[aNewSection.size()-1] == ']' )
					{
						aNewSection.resize(aNewSection.size()-1);
						aSection.swap(aNewSection);
					}
					aState = ePIState_Whitespace;
					break;
				default:
					aNewSection.push_back(c);
				}
				break;

			case ePIState_Key:
				// Look for '=' to end key
				if( c == '=' )
				{// Switch from parsing key to value
					aKey = trim(aKey);
					aState = ePIState_Value;
					aValue.clear();
				}
				else if( c == '\r' || c == '\n' || c == '\0' )
				{// Abort - invalid key
					aState = ePIState_Whitespace;
				}
				else
				{
					aKey.push_back(c);
				}
				break;

			case ePIState_Value:
				// Look for eol to end value
				if( c == '\r' || c == '\n' || c == '\0' )
				{// Value string complete, time to process it!
					aValue = trim(aValue);
					theCallbackFunc(aSection, aKey, aValue, theUserData);
					aState = ePIState_Whitespace;
				}
				else
				{
					aValue.push_back(c);
				}
				break;

			case ePIState_Comment:
				// Look for eol to end comment
				if( c == '\r' || c == '\n' || c == '\0' )
					aState = ePIState_Whitespace;
				break;
			}
		}
	}

	aFile.close();
}


static void setPropertyInINI(
	const std::string& theFilePath,
	const std::string& theSection,
	const std::string& theKey,
	const std::string& theValue)
{
	// Open source file
	const std::wstring& aFilePathW = widen(theFilePath);
	std::ifstream aFile(aFilePathW.c_str(), std::ios::binary);
	if( !aFile.is_open() )
	{
		const std::string anError =
			strFormat("Could not open file %s", theFilePath.c_str());
		if( sLoadedProfileIdx )
			logError(anError.c_str());
		else
			Dialogs::showError(anError);
		return;
	}

	// Create temp output file
	const std::wstring& aTmpPath = getTempFilePathFor(aFilePathW);
	std::ofstream aTmpFile(
		aTmpPath.c_str(),
		std::ios::binary | std::ios::trunc);
	if( !aTmpFile.is_open() )
	{
		const std::string anError =
			strFormat("Could not create temp file %ls", aTmpPath.c_str());
		if( sLoadedProfileIdx )
			logError(anError.c_str());
		else
			Dialogs::showError(anError);
		aFile.close();
		return;
	}

	// Prepare buffer
	// +1 on size is to accommodate an extra newline character when
	// reach end of file for simpler parsing code
	char aBuffer[kINIFileBufferSize+1];
	std::streamsize aBufferSize = kINIFileBufferSize;
	std::string aCheckStr;
	const std::string& aCmpSection = condense(theSection);
	const std::string& aCmpKey = condense(theKey);

	enum
	{
		eSKVState_FindSection,
		eSKVState_CheckSection,
		eSKVState_SkipSectionLine,
		eSKVState_FindKey,
		eSKVState_CheckKey,
		eSKVState_FinishKeyLine,
		eSKVState_SkipKeyLine,
		eSKVState_ValueLine,
		eSKVState_Finished,
	} aState = eSKVState_FindSection;

	// Parse the INI file to find start and end of segment to replace
	const std::fstream::pos_type kInvalidFilePos = -1;
	std::fstream::pos_type aReplaceStartPos = kInvalidFilePos;
	std::fstream::pos_type aReplaceEndPos = kInvalidFilePos;
	std::fstream::pos_type anEndOfValidSection = kInvalidFilePos;
	std::fstream::pos_type aCurrFilePos = aFile.tellg();
	std::fstream::pos_type aValidFileCharsEnd = kInvalidFilePos;

	if( theSection.empty() )
	{
		aState = eSKVState_FindKey;
		anEndOfValidSection = 0;
	}

	while(aFile.good() && aState != eSKVState_Finished)
	{
		// Read next chunk from file
		aFile.read(aBuffer, aBufferSize);
		if( aFile.eof() || aFile.gcount() < aBufferSize )
		{// Put eol at end of file in case there wasn't one already
			aBufferSize = aFile.gcount() + 1;
			aBuffer[aBufferSize-1] = '\n';
			DBG_ASSERT(aBufferSize <= ARRAYSIZE(aBuffer));
		}
		else if( aFile.bad() )
		{
			const std::string anError =
				strFormat("Unknown error reading %s", theFilePath.c_str());
			if( sLoadedProfileIdx )
				logError(anError.c_str());
			else
				Dialogs::showError(anError);
			aFile.close();
			return;
		}

		for(int i = 0; i < aBufferSize && aState != eSKVState_Finished; ++i)
		{// Step through buffer character-by-character
			const char c = aBuffer[i];
			switch(aState)
			{
			case eSKVState_FindSection:
				// Look for a section
				if( c == '[' )
				{
					aState = eSKVState_CheckSection;
					aCheckStr.clear();
				}
				else if( u8(c) > ' ' )
				{
					aState = eSKVState_SkipSectionLine;
				}
				break;

			case eSKVState_CheckSection:
				// Look for endline after ']' to end section
				switch(c)
				{
				case '\r': case '\n': case '\0':
					aState = eSKVState_FindSection;
					aCheckStr = condense(aCheckStr);
					if( aCheckStr.size() > 1 &&
						aCheckStr[aCheckStr.size()-1] == ']' )
					{
						aCheckStr.resize(aCheckStr.size()-1);
						if( aCheckStr == aCmpSection )
						{
							aState = eSKVState_FindKey;
							anEndOfValidSection = aCurrFilePos;
						}
						else if( aCmpSection.empty() )
						{
							aState = eSKVState_Finished;
						}
					}
					break;
				default:
					aCheckStr.push_back(c);
					break;
				}
				break;

			case eSKVState_SkipSectionLine:
				// Look for end of line than resume section search
				if( c == '\r' || c == '\n' || c == '\0' )
					aState = eSKVState_FindSection;
				break;

			case eSKVState_FindKey:
				// Look for start of a key
				if( c == '[' )
				{
					aState = eSKVState_CheckSection;
					aCheckStr.clear();
				}
				else if( c == '#' || c == ';' )
				{
					aState = eSKVState_SkipKeyLine;
				}
				else if( u8(c) > ' ' )
				{
					aState = eSKVState_CheckKey;
					aCheckStr.clear();
					aCheckStr.push_back(c);
				}
				break;

			case eSKVState_CheckKey:
				// Look for '=' to end key
				if( c == '=' )
				{// End of the key - check if this is the one being looked for
					if( condense(aCheckStr) == aCmpKey )
					{// Found starting position to replace with new characters!
						aReplaceStartPos = aCurrFilePos;
						aReplaceStartPos += std::fstream::off_type(1);
						aState = eSKVState_ValueLine;
					}
					else
					{// Not the right key, but could be last key of section
						aState = eSKVState_FinishKeyLine;
					}
				}
				else if( c == '\r' || c == '\n' || c == '\0' )
				{// Abort - invalid key
					aState = eSKVState_FindKey;
				}
				else
				{
					aCheckStr.push_back(c);
				}
				break;

			case eSKVState_FinishKeyLine:
				// Continue to end of line then resume key search
				if( c == '\r' || c == '\n' || c == '\0' )
				{
					aState = eSKVState_FindKey;
					anEndOfValidSection = aCurrFilePos;
				}
				break;

			case eSKVState_SkipKeyLine:
				// Look for end of line then resume key search
				if( c == '\r' || c == '\n' || c == '\0' )
					aState = eSKVState_FindKey;
				break;

			case eSKVState_ValueLine:
				// Look for eol to end section to replace
				if( c == '\r' || c == '\n' || c == '\0' )
				{
					aReplaceEndPos = aCurrFilePos;
					aState = eSKVState_Finished;
				}
				break;
			}
			aCurrFilePos += std::fstream::off_type(1);
		}
	}

	// Find the last non-whitespace character of the file overall
	aFile.clear();
	aFile.seekg(0, std::ios::end);
	while( aFile.tellg() != std::fstream::pos_type(0) )
	{
		aFile.seekg(-1, std::ios::cur);
		if( u8(aFile.peek()) > ' ' )
			break;
	}
	if( aFile.tellg() != std::fstream::pos_type(0) ||
		(aFile.peek() != EOF && u8(aFile.peek()) > ' ') )
	{
		aFile.seekg(1, std::ios::cur);
		aValidFileCharsEnd = aFile.tellg();
	}
	aFile.clear();

	// Decide what to write and where exactly from info gathered above
	std::string aWriteString;
	if( aReplaceStartPos != kInvalidFilePos )
	{
		// Found the existing key, just write new value
		DBG_ASSERT(aReplaceEndPos != kInvalidFilePos);
		aWriteString = std::string(" ") + trim(theValue);
	}
	else if( anEndOfValidSection == std::fstream::pos_type(0) )
	{
		// Write new entry right at start of the file
		DBG_ASSERT(theSection.empty());
		aReplaceStartPos = aReplaceEndPos = 0;
		aWriteString = trim(theKey) + " = " + trim(theValue);
		if( aValidFileCharsEnd != kInvalidFilePos )
			aWriteString += kEndOfLine + kEndOfLine;
		
	}
	else if( anEndOfValidSection != kInvalidFilePos )
	{
		// Found section, write key and value
		aReplaceStartPos = aReplaceEndPos = anEndOfValidSection;
		aWriteString = kEndOfLine + trim(theKey) + " = " + trim(theValue);
	}
	else
	{
		// Found nothing - write section, key, and value
		aReplaceStartPos = aValidFileCharsEnd;
		aFile.seekg(0, std::ios::end);
		aReplaceEndPos = kInvalidFilePos;
		if( aReplaceStartPos != kInvalidFilePos )
			aWriteString = kEndOfLine + kEndOfLine;
		aWriteString += "[" + trim(theSection) + "]" + kEndOfLine;
		aWriteString += trim(theKey) + " = " + trim(theValue);
	}

	// Write aFile 0->aReplaceStartPos to temp file
	if( aReplaceStartPos != kInvalidFilePos &&
		aReplaceStartPos > std::fstream::pos_type(0) )
	{
		aFile.seekg(0, std::ios::beg);
		aCurrFilePos = aFile.tellg();
		while(aCurrFilePos < aReplaceStartPos && aFile.good())
		{
			std::streamsize aBytesToRead = aReplaceStartPos - aCurrFilePos;
			aBytesToRead = MIN(aBytesToRead, kINIFileBufferSize);
			aFile.read(aBuffer, aBytesToRead);
			aTmpFile.write(aBuffer, aFile.gcount());
			aCurrFilePos += aFile.gcount();
		}
	}

	// Write new data
	aTmpFile << aWriteString;

	// Write aReplaceEndPos->aValidFileCharsEnd to temp file
	if( aReplaceEndPos != kInvalidFilePos &&
		aValidFileCharsEnd != kInvalidFilePos &&
		aValidFileCharsEnd > aReplaceEndPos )
	{
		aFile.seekg(aReplaceEndPos, std::ios::beg);
		aCurrFilePos = aFile.tellg();
		while(aCurrFilePos < aValidFileCharsEnd && aFile.good())
		{
			std::streamsize aBytesToRead = aValidFileCharsEnd - aCurrFilePos;
			aBytesToRead = MIN(aBytesToRead, kINIFileBufferSize);
			aFile.read(aBuffer, aBytesToRead);
			aTmpFile.write(aBuffer, aFile.gcount());
			aCurrFilePos += aFile.gcount();
		}
	}

	// Write a single blank line at end of file
	aTmpFile.write(kEndOfLine.c_str(), kEndOfLine.size());

	// Close both files
	aFile.close();
	aTmpFile.close();

	// Replace original file with temp file (temp file is moved/consumed)
	if( !ReplaceFile(aFilePathW.c_str(), aTmpPath.c_str(),
			NULL, REPLACEFILE_IGNORE_MERGE_ERRORS, NULL, NULL) )
	{
		const std::string anError =
			strFormat("Failed to modify file %s!", theFilePath.c_str());
		if( sLoadedProfileIdx )
			logError(anError.c_str());
		else
			Dialogs::showError(anError);
	}
}


static void generateResourceFile(const ResourceFile& theResFile)
{
	const std::string& aFilePath =
		profileNameToFilePath(theResFile.fileName);

	if( !writeResourceToFile(theResFile.resID,
			L"TEXT", widen(aFilePath).c_str()) )
	{
		logFatalError("Unable to write Profile data to file %s\n",
			aFilePath.c_str());
		return;
	}

	if( theResFile.version )
	{
		setPropertyInINI(aFilePath,
			"", kAutoGenVersionKey,
			toString(theResFile.version));
	}
}


static void getProfileListCallback(
	const std::string& theSection,
	const std::string& theName,
	const std::string& theValue,
	void*)
{
	if( theValue.empty() )
		return;
	DBG_ASSERT(theSection.empty());
	const std::string& aProfileNameKey = condense(theName);
	const std::string& aProfileKeyPrefix = condense(kProfileKeyPrefix);
	if( aProfileNameKey.compare(0,
			aProfileKeyPrefix.length(), aProfileKeyPrefix) == 0 )
	{// Profile name entry
		const int aProfileNum =
			stringToInt(aProfileNameKey.substr(aProfileKeyPrefix.length()));
		if( sDisplayedProfileList.size() < size_t(aProfileNum) )
			sDisplayedProfileList.resize(aProfileNum);
		sDisplayedProfileList[aProfileNum-1] = extractProfileName(theValue);
	}
	else if( aProfileNameKey == condense(kAutoLoadProfileKey) )
	{// Auto-load profile entry
		gProfileToLoad = theValue;
	}
}


static void addParentCallback(
	const std::string& theSection,
	const std::string& theName,
	const std::string& theValue,
	void* theChildProfileIdx)
{
	DBG_ASSERT(theSection.empty());
	DBG_ASSERT(size_t(*((int*)theChildProfileIdx)) < size_t(sProfiles.size()));

	if( theValue.empty() )
		return;
	if( condense(theName) == "PARENTPROFILE" || condense(theName) == "PARENT" )
	{
		int aParentProfileID =
			sProfiles.findOrAddIndex(extractProfileName(theValue));
		// Ignore setting core profile as parent - that's assumed anyway
		if( aParentProfileID == 0 )
		{
			sProfiles.vals()[*((int*)theChildProfileIdx)].parent.clear();
			return;
		}
		ProfileData& aParentProfile = sProfiles.vals()[aParentProfileID];
		if( aParentProfile.path.empty() )
		{
			// Try path with existing spaces first in case manually added
			aParentProfile.path = profileNameToFilePath(
				sProfiles.keys()[aParentProfileID], false);
			if( !fileExists(aParentProfile.path) )
			{// Check again with spaces replaced by '_'
				aParentProfile.path = profileNameToFilePath(
					sProfiles.keys()[aParentProfileID], true);
			}
		}
		aParentProfile.isAParent = true;
		sProfiles.vals()[*((int*)theChildProfileIdx)].parent =
			sProfiles.keys()[aParentProfileID];
		if( !fileExists(aParentProfile.path) )
		{// File not found - but maybe referencing a resource base file?
			const std::string& aCmpName =
				condense(sProfiles.keys()[aParentProfileID]);
			for(int i = 0; i < ARRAYSIZE(kResTemplateBase); ++i)
			{
				if( condense(kResTemplateBase[i].fileName) == aCmpName )
				{
					generateResourceFile(kResTemplateBase[i]);
					sNewBaseProfileIdx = aParentProfileID;
					break;
				}
			}
		}
		if( !fileExists(aParentProfile.path) )
		{// File still not found - maybe referencing a resource default file?
			const std::string& aCmpName =
				condense(sProfiles.keys()[aParentProfileID]);
			for(int i = 0; i < ARRAYSIZE(kResTemplateDefault); ++i)
			{
				if( condense(kResTemplateDefault[i].fileName) == aCmpName )
				{
					generateResourceFile(kResTemplateDefault[i]);
					break;
				}
			}
		}
		if( !fileExists(aParentProfile.path) )
		{// File still not found - report error
			Dialogs::showError(strFormat(
				"Could not find '%s' Profile's parent: '%s' (%s)",
				sProfiles.keys()[*((int*)theChildProfileIdx)].c_str(),
				theValue.c_str(),
				aParentProfile.path.c_str()));
			return;
		}
		// Check for infinite parent loop
		while(!sProfiles.vals()[aParentProfileID].parent.empty())
		{
			const int aCheckProfileID = sProfiles.quickFindIndex(
				sProfiles.vals()[aParentProfileID].parent);
			if( aCheckProfileID == *((int*)theChildProfileIdx) )
			{
				Dialogs::showError(strFormat(
					"Infinite profile parenting loop detected - "
					"Profile '%s' ends up as a parent of itself!",
					sProfiles.keys()[*((int*)theChildProfileIdx)].c_str()));
				sProfiles.vals()[aParentProfileID].parent.clear();
				aParentProfileID = 0;
			}
			else
			{
				aParentProfileID = aCheckProfileID;
			}
		}
	}
}


static void generateKnownIssuesRTF(std::string theIssuesList)
{
	sNeedShowKnownIssues = false;
	sKnownIssuesRTF.clear();
	StringToValueMap<bool> anIssuesMap;
	while(!theIssuesList.empty())
		anIssuesMap.setValue(breakOffNextItem(theIssuesList), true);

	HRSRC hRes = FindResource(null,
		MAKEINTRESOURCE(IDR_TEXT_KNOWN_ISSUES), L"TEXT");
	DBG_ASSERT(hRes);
	HGLOBAL hData = LoadResource(null, hRes);
	DBG_ASSERT(hData);
	const char* aResStr = (const char*)LockResource(hData);
	sKnownIssuesRTF = aResStr;
	FreeResource(hRes);

	// Find which issues to display and filter out the rest
	std::pair<std::string::size_type, std::string::size_type> aTagCoords;
	aTagCoords = findStringTag(sKnownIssuesRTF, 0, "|", '|');
	std::string anIssueName;
	std::string aTagContents;
	while(aTagCoords.first != std::string::npos)
	{
		aTagContents = sKnownIssuesRTF.substr(
			aTagCoords.first+1, aTagCoords.second-2);
		anIssueName = breakOffItemBeforeChar(aTagContents);
		if( anIssueName == "NONE" )
		{// Show contents only if have no issues so far
			// This should be the last tag in the .rtf resource file!
			if( sNeedShowKnownIssues )
				aTagContents.clear();
		}
		else if( anIssuesMap.contains(anIssueName) )
		{// Note that have found at least one known issue
			sNeedShowKnownIssues = true;
		}
		else
		{// Not a known issue for this title - strip entirely
			aTagContents.clear();
		}
		sKnownIssuesRTF.replace(
			aTagCoords.first,
			aTagCoords.second,
			aTagContents);
		aTagCoords = findStringTag(sKnownIssuesRTF, 0, "|", '|');
	}
}


static void readBaseGameSettingsCallback(
	const std::string& theSection,
	const std::string& theName,
	const std::string& theValue,
	void* theAppInfo)
{
	if( !theAppInfo || theValue.empty() )
		return;

	BaseGameSettings* theSettings = (BaseGameSettings*)(theAppInfo);
	if( condense(theSection) == condense(kBaseGameSettingsSection) )
	{
		if( condense(theName) == condense(kAutoLaunchAppKey) )
			theSettings->autoLaunchAppPath = theValue;
		if( condense(theName) == condense(kAutoLaunchAppParamsKey) )
			theSettings->autoLaunchAppParams = theValue;
		if( condense(theName) == condense(kAutoQuitWithAppKey))
			theSettings->autoQuitWithTargetApp = theValue;
		if( condense(theName) == condense(kAutoQuitWithWindowKey))
			theSettings->autoQuitWithTargetWin = theValue;
		if( condense(theName) == condense(kMainWindowNameKey))
			theSettings->mainWindowName = theValue;
		if( condense(theName) == condense(kKnownIssuesKey) )
			theSettings->knownIssuesList = theValue;
	}
}


static BaseGameSettings getBaseGameSettings(const std::string& theProfilePath)
{
	BaseGameSettings result;

	parseINI(
		readBaseGameSettingsCallback,
		theProfilePath,
		eParseMode_Sections,
		&result);

	return result;
}


static void writeBaseGameSettingsChanges(
	const std::string& theProfilePath,
	const BaseGameSettings& theDefaultSettings,
	const BaseGameSettings& theCustomSettings)
{
	if( !theCustomSettings.autoLaunchAppPath.empty() ||
		!theDefaultSettings.autoLaunchAppPath.empty() )
	{
		setPropertyInINI(
			theProfilePath,
			kBaseGameSettingsSection, kAutoLaunchAppKey,
			theCustomSettings.autoLaunchAppPath);
	}
	if( !theCustomSettings.autoLaunchAppParams.empty() ||
		!theDefaultSettings.autoLaunchAppParams.empty() )
	{
		setPropertyInINI(
			theProfilePath,
			kBaseGameSettingsSection, kAutoLaunchAppParamsKey,
			theCustomSettings.autoLaunchAppParams);
	}
	if( !theCustomSettings.autoQuitWithTargetApp.empty() ||
		!theDefaultSettings.autoQuitWithTargetApp.empty() )
	{
		setPropertyInINI(
			theProfilePath,
			kBaseGameSettingsSection, kAutoQuitWithAppKey,
			theCustomSettings.autoQuitWithTargetApp);
	}
	if( !theCustomSettings.autoQuitWithTargetWin.empty() ||
		!theDefaultSettings.autoQuitWithTargetWin.empty() )
	{
		setPropertyInINI(
			theProfilePath,
			kBaseGameSettingsSection, kAutoQuitWithWindowKey,
			theCustomSettings.autoQuitWithTargetWin);
	}
	if( !theCustomSettings.mainWindowName.empty() ||
		!theDefaultSettings.mainWindowName.empty() )
	{
		setPropertyInINI(
			theProfilePath,
			kBaseGameSettingsSection, kMainWindowNameKey,
			theCustomSettings.mainWindowName);
	}
}


static void setAutoLoadProfile(int theProfileIndex)
{
	if( theProfileIndex == sAutoLoadProfileIdx )
		return;

	DBG_ASSERT(theProfileIndex < sProfiles.size());
	sAutoLoadProfileIdx = theProfileIndex;

	setPropertyInINI(
		sProfiles.vals()[0].path, "",
		kAutoLoadProfileKey,
		sAutoLoadProfileIdx > 0
			? sProfiles.keys()[sAutoLoadProfileIdx]
			: std::string());
}


static void readVersionCallback(
	const std::string& /*theSection*/,
	const std::string& theName,
	const std::string& theValue,
	void* theVersion)
{
	if( !theVersion || theValue.empty() )
		return;

	int* aVersion = (int*)(theVersion);
	if( condense(theName) == condense(kAutoGenVersionKey) )
		*aVersion = stringToInt(theValue);
}


static void addSystemCheckVarsToProfile(const std::string& theFilePath)
{
	bool runningInLinux = false;

	HKEY hKey;
	WCHAR aWStr[256];
	DWORD aType, aSize;

	// Check for Wine
	if( RegOpenKeyEx(HKEY_LOCAL_MACHINE,
			L"Software\\Wine", 0, KEY_READ, &hKey) == ERROR_SUCCESS )
	{
		runningInLinux = true;
		RegCloseKey(hKey);
	}
	else if( RegOpenKeyEx(HKEY_LOCAL_MACHINE,
				L"Software\\Microsoft\\Windows NT\\CurrentVersion",
				0, KEY_READ, &hKey) == ERROR_SUCCESS)
	{
		aSize = sizeof(aWStr);
		if( RegQueryValueEx(hKey, L"Wine", NULL, &aType,
				(LPBYTE)aWStr, &aSize) == ERROR_SUCCESS )
		{
			runningInLinux = true;
		}
		RegCloseKey(hKey);
	}

	if( !runningInLinux )
		return;

	setPropertyInINI(
		theFilePath, "Variables", kLinuxVarName, "true");

	// Check for Wayland, which blocks icon copy feature
	bool usingWayland = false;
	aSize = sizeof(aWStr) / sizeof(WCHAR);
	if( GetEnvironmentVariable(
			L"WAYLAND_DISPLAY", aWStr, aSize) > 0 ||
		GetEnvironmentVariable(
			L"GAMESCOPE_WAYLAND_DISPLAY", aWStr, aSize) > 0 )
	{
		usingWayland = true;
	}
	else if( GetEnvironmentVariable(L"XDG_SESSION_TYPE", aWStr, aSize) > 0 )
	{
		const std::string& aStr = lower(narrow(aWStr));
		if( aStr.find("wayland") != std::string::npos )
			usingWayland = true;
	}

	if( !usingWayland &&
		RegOpenKeyEx(HKEY_CURRENT_USER,
			L"Software\\Wine\\Drivers",
			0, KEY_READ, &hKey) == ERROR_SUCCESS )
	{
		aSize = sizeof(aWStr);
		if( RegQueryValueEx(hKey, L"Graphics", NULL, &aType,
				(LPBYTE)aWStr, &aSize) == ERROR_SUCCESS )
		{
			const std::string& aStr = lower(narrow(aWStr));
			if( aStr.find("wayland") != std::string::npos )
				usingWayland = true;
		}
		RegCloseKey(hKey);
	}

	if( usingWayland )
	{
		setPropertyInINI(
			theFilePath, "Variables", kCopyIconsVarName, "Not supported");
		setPropertyInINI(
			theFilePath, "Variables", kCopyExcludeOverlaysVarName, "No");
	}
}


static void checkForOutdatedFileVersion(const std::string& theFilePath)
{
	const ResourceFile* theMatchingResource = NULL;
	bool matchingResourceIsCore = false;
	bool matchingResourceIsBase = false;
	if( isSamePath(theFilePath,
			profileNameToFilePath(kResTemplateCore.fileName)) )
	{
		theMatchingResource = &kResTemplateCore;
		matchingResourceIsCore = true;
	}
	if( !theMatchingResource )
	{
		for(int i = 0; i < ARRAYSIZE(kResTemplateBase); ++i)
		{
			const std::string& aResPath =
				profileNameToFilePath(kResTemplateBase[i].fileName);
			if( isSamePath(theFilePath, aResPath) )
			{
				theMatchingResource = &kResTemplateBase[i];
				matchingResourceIsBase = true;
				break;
			}
		}
	}
	if( !theMatchingResource )
	{
		for(int i = 0; i < ARRAYSIZE(kResTemplateDefault); ++i)
		{
			const std::string& aResPath =
				profileNameToFilePath(kResTemplateDefault[i].fileName);
			if( isSamePath(theFilePath, aResPath) )
			{
				theMatchingResource = &kResTemplateDefault[i];
				break;
			}
		}
	}
	// Only replace custom files when set to always refresh, and only for first
	#ifdef ALWAYS_REFRESH_DEFAULT_INI
	if( !theMatchingResource && !sLoadedProfileIdx )
	{
		for(int i = 0; i < ARRAYSIZE(kResTemplateCustom); ++i)
		{
			const std::string& aResPath =
				profileNameToFilePath(kResTemplateCustom[i].fileName);
			if( isSamePath(theFilePath, aResPath) )
			{
				theMatchingResource = &kResTemplateCustom[i];
				break;
			}
		}
	}
	#endif
	if( !theMatchingResource )
		return;

	EResult aResult = eResult_Yes;
	#ifndef ALWAYS_REFRESH_DEFAULT_INI
	// Check for version number stored in the file
	int aFileVersion = 0;
	parseINI(
		readVersionCallback,
		theFilePath,
		eParseMode_Header,
		&aFileVersion);

	// If version number not specified (or set to 0), ignore it
	if( hadFatalError() || !aFileVersion )
		return;
	// If file version number >= expected, no change needed
	if( aFileVersion >= theMatchingResource->version )
		return;
	// File is outdated - prompt to replace it!
	aResult = Dialogs::yesNoPrompt(strFormat(
			"File '%s' was auto-generated by a previous version of this app."
			"Would you like to replace it with an updated version?\n\n"
			"Any changes made to it since it was generated%swill be lost!",
			getFileName(theFilePath).c_str(),
			matchingResourceIsCore ? " (besides the profile list) " :
			matchingResourceIsBase ?
				" (besides auto-launch/quit app setup) " : " "),
			"Update outdated generated file", true);
	#endif
	if( aResult == eResult_Yes )
	{// Update the generated file to new version
		BaseGameSettings aCustomSettings;
		if( matchingResourceIsBase )
			aCustomSettings = getBaseGameSettings(theFilePath);
		generateResourceFile(*theMatchingResource);
		if( matchingResourceIsCore )
		{// Restore expected customizations made directly to core profile
			// Auto-load profile name
			setPropertyInINI(
				theFilePath, "",
				kAutoLoadProfileKey,
				sAutoLoadProfileIdx > 0
					? sProfiles.keys()[sAutoLoadProfileIdx]
					: std::string());
			// Profile display order
			for(int i = 0, end = intSize(sDisplayedProfileList.size());
				i < end; ++i)
			{
				setPropertyInINI(
					theFilePath, "",
					std::string(kProfileKeyPrefix) + toString(i+1),
					sDisplayedProfileList[i]);
			}
			// System check results (Linux etc)
			addSystemCheckVarsToProfile(theFilePath);
		}
		else if( matchingResourceIsBase )
		{// Restore base game setting changes to regenerated Base file
			const BaseGameSettings& aDefaultSettings =
				getBaseGameSettings(theFilePath);

			writeBaseGameSettingsChanges(
				theFilePath, aDefaultSettings, aCustomSettings);

			#ifndef ALWAYS_REFRESH_DEFAULT_INI
			// Generate known issues and, if there are any, display them now,
			// in case they have changed since previous version of app
			generateKnownIssuesRTF(aDefaultSettings.knownIssuesList);
			if( sNeedShowKnownIssues )
			{
				Dialogs::showKnownIssues();
				sNeedShowKnownIssues = false;
			}
			#endif
		}
	}
	else if( aResult == eResult_No )
	{
		// Update the file's version number so won't ask again
		setPropertyInINI(
			theFilePath, "",
			kAutoGenVersionKey,
			toString(theMatchingResource->version));
	}
	// else if( aResult == eResult_Cancel )
	// Ignore this time since are in-game already - ask again next time!
}


static void fillProfileFileList(
	int theProfileID,
	std::vector<std::string>& theFileList)
{
	DBG_ASSERT(size_t(theProfileID) < size_t(sProfiles.size()));
	if( sProfiles.vals()[theProfileID].parent.empty() )
	{// Core must be the parent profile - add it first
		theFileList.push_back(sProfiles.vals()[0].path);
	}
	else
	{// Add parent profile first
		fillProfileFileList(
			sProfiles.quickFindIndex(sProfiles.vals()[theProfileID].parent),
			theFileList);
	}
	if( fileExists(sProfiles.vals()[theProfileID].path) )
		theFileList.push_back(sProfiles.vals()[theProfileID].path);
}


static bool userEditProfile(int theProfileID, bool firstProfile)
{
	// Generate list of files to possibly edit (using recursion for ordering)
	std::vector<std::string> aFileList;
	fillProfileFileList(theProfileID, aFileList);

	// Note file modification times to check if any actual changes are made
	std::vector<FILETIME> aLastFileModTime;
	aLastFileModTime.resize(aFileList.size());
	for(int i = 0, end = intSize(aFileList.size()); i < end; ++i)
		aLastFileModTime[i] = getFileLastModTime(aFileList[i]);

	Dialogs::profileEdit(aFileList, firstProfile);

	// Test if any actual changes were made to any of the profile's files
	for(size_t i = 0; i < aFileList.size(); ++i)
	{
		if( !fileExists(aFileList[i]) )
			return true;
		const FILETIME& aNewFileTime = getFileLastModTime(aFileList[i]);
		if( CompareFileTime(&aLastFileModTime[i], &aNewFileTime) != 0 )
			return true;
	}

	return false;
}


static void logPropVarDependency(VarPropDependency theDep, bool init)
{
	if( init )
	{
		// Just push on to the list and it will be sorted in later
		sVarPropDepList.push_back(theDep);
		return;
	}

	std::vector<VarPropDependency>::iterator itr = std::lower_bound(
		sVarPropDepList.begin(), sVarPropDepList.end(), theDep);
	if( itr == sVarPropDepList.end() || !(*itr == theDep) )
		sVarPropDepList.insert(itr, theDep);
}


static bool checkVarCompare(
	const std::string& theVarStr,
	const std::string& theParamStr,
	double theVarNum, double theParamNum,
	char theOperator)
{
	switch(theOperator)
	{
	case '<': return theVarNum < theParamNum;
	case '(': return theVarNum <= theParamNum;
	case '>': return theVarNum > theParamNum;
	case ')': return theVarNum >= theParamNum;
	case '?': return stringToBool(theVarStr);
	case '=':
		if( !_isnan(theVarNum) && !_isnan(theParamNum) )
			return theVarNum == theParamNum;
		return condense(theVarStr) == condense(theParamStr);
	case '!':
		if( !_isnan(theVarNum) && !_isnan(theParamNum) )
			return theVarNum != theParamNum;
		return condense(theVarStr) != condense(theParamStr);
	default:
		DBG_ASSERT(false && "Unhandled conditional operator");
		return false;
	}
}


static std::string varSelectString(
	const std::string& theVarStr,
	const std::string& theTagStr,
	size_t thePos)
{
	const double theVarNum = stringToDouble(theVarStr, true);
	std::string aCaseStr, aValStr, aStr;
	double aCaseNum = -1.0;
	while(thePos < theTagStr.size())
	{
		char anOpC = '=';
		aStr = fetchNextItem(theTagStr, thePos, ":,]}");
		if( theTagStr[thePos] == ':' )
		{
			// Check for an operator at start of case
			int anOpCharCount = 0;
			switch(aStr[0])
			{
			case '~': case '!':
				anOpC = '!';
				// Ignore extra '=' for '!=' or '~='
				if( aStr[++anOpCharCount] == '=' )
					++anOpCharCount;
				break;
			case '<':
				if( aStr[++anOpCharCount] == '>' )
				{// Treat <> as alternate form of '!'
					anOpC = '!';
					++anOpCharCount;
				}
				else if( aStr[anOpCharCount] == '=' )
				{// Use '(' to mean less-than-or-equal (internally only)
					anOpC = '(';
					++anOpCharCount;
				}
				else
				{
					anOpC = '<';
				}
				break;
			case '>':
				if( aStr[++anOpCharCount] == '=' )
				{// Use ')' to mean less-than-or-equal (internally only)
					anOpC = ')';
					++anOpCharCount;
				}
				else
				{
					anOpC = '>';
				}
				break;
			case '=':
				// Ignore extra '='
				if( aStr[++anOpCharCount] == '=' )
					++anOpCharCount;
				break;
			}
			aCaseStr = aStr.substr(anOpCharCount);
			aCaseNum = stringToDouble(aCaseStr, true);
			aValStr = fetchNextItem(theTagStr, ++thePos, ",]}");
			if( (_isnan(aCaseNum) || _isnan(theVarNum)) &&
				anOpC != '!' && anOpC != '=' )
			{
				logError("Variable select case comparison of '%s %s' "
					"expected numeric values for this operator type!",
					theVarStr.c_str(), aStr.c_str());
				// Skip this invalid case, or return it if last one anyway
				if( theTagStr[thePos++] != ',' )
					return aValStr;
				continue;
			}
		}
		else
		{
			// No case found - must be only value was specified
			// Use previous case + 1 as assumed next case if using numbers
			if( !_isnan(aCaseNum) )
				aCaseNum = floor(aCaseNum) + 1.0;
			// Assume this is instead the value string
			aValStr = aStr;
		}

		// If reached end of [] block without returning anything yet, return
		// last value found as the default (even if it wouldn't have matched)
		if( theTagStr[thePos++] != ',' )
			return aValStr;

		// Check if case matches and if so return value found as replacement
		if( checkVarCompare(theVarStr, aCaseStr, theVarNum, aCaseNum, anOpC) )
			return aValStr;
	}

	return aValStr;
}


static std::string varTagToString(
	const std::string& theVarContents,
	const std::string& theTagStr,
	const size_t theFirstOperatorPos,
	VarPropDependency* theVarDep = null,
	bool init = false)
{
	std::string result = theVarContents;
	// Replace quoted string with un-trimmed contents
	if( result.size() >= 2 &&
		((result[0] == '"' && result[result.size()-1] == '"') ||
		 (result[0] == '\'' && result[result.size()-1] == '\'')) )
	{
		result = result.substr(1, result.size()-2);
	}

	DBG_ASSERT(theFirstOperatorPos < theTagStr.size());
	size_t aPos = theFirstOperatorPos;
	// Figure out what operator we're dealing with (some use 2 chars)
	u8 anOpC = theTagStr[aPos++];
	const char* aNextDel = "?}";
	switch(anOpC)
	{
	case '}':
		return result;
	case '?':
		aNextDel = ":}";
		break;
	case '~':
		anOpC = '!';
		// fall through
	case '!':
		// Ignore extra '=' for '!=' or '~='
		if( theTagStr[aPos] == '=' )
			++aPos;
		break;
	case '<':
		if( theTagStr[aPos] == '>' )
		{// Treat <> as alternate form of '!'
			anOpC = '!';
			++aPos;
		}
		else if( theTagStr[aPos] == '=' )
		{// Use '(' to mean less-than-or-equal (internally only)
			anOpC = '(';
			++aPos;
		}
		break;
	case '>':
		if( theTagStr[aPos] == '=' )
		{// Use ')' to mean less-than-or-equal (internally only)
			anOpC = ')';
			++aPos;
		}
		break;
	case '=':
		// Ignore extra '='
		if( theTagStr[aPos] == '=' )
			++aPos;
		break;
	case '/':
		if( theTagStr[aPos] == '~' )
		{// Use /~ to for mod operator
			anOpC = '%';
			++aPos;
		}
		// fall through
	case '+': case '-': case '*':
		aNextDel = "}+*/?[!~<>="; // to warn of multi-operator use (except -)
		break;
	case '.':
		// Not really an operator, so find the actual operator next (if any)
		aNextDel = "}+-*/?[!~<>=.";
		break;
	case '[':
		return varSelectString(theVarContents, theTagStr, aPos);
	default:
		DBG_ASSERT(false && "Unhandled operator character");
	}

	// Get first parameter for operator
	const std::string& aParam = fetchNextItem(theTagStr, aPos, aNextDel);

	// Check for special .anchor, .offset, .x/xs, and .y/ys for coord vars,
	// as well as .sum, .int, .round, .floor, and .ceil for sum vars
	if( anOpC == '.' )
	{
		enum EMemberType {
			eMemberType_Unknown,
			eMemberType_X,
			eMemberType_Y,
			eMemberType_XScaled,
			eMemberType_YScaled,
			eMemberType_Offset,
			eMemberType_Anchor,
			eMemberType_Sum,
			eMemberType_Round,
			eMemberType_Floor,
			eMemberType_Ceil,
			eMemberType_Abs,

			eMemberType_LastCoordType = eMemberType_Anchor
		};
		struct NameToEnumMapper
		{
			typedef StringToValueMap<EMemberType, u8> NameToEnumMap;
			NameToEnumMap map;
			NameToEnumMapper()
			{
				struct { const char* str; EMemberType val; }
				kEntries[] = {
					{ "x",			eMemberType_X		},
					{ "y",			eMemberType_Y		},
					{ "xs",			eMemberType_XScaled	},
					{ "ys",			eMemberType_YScaled	},
					{ "offset",		eMemberType_Offset	},
					{ "anchor",		eMemberType_Anchor	},
					{ "sum",		eMemberType_Sum		},
					{ "int",		eMemberType_Round	},
					{ "integer",	eMemberType_Round	},
					{ "num",		eMemberType_Round	},
					{ "round",		eMemberType_Round	},
					{ "floor",		eMemberType_Floor	},
					{ "ceil",		eMemberType_Ceil	},
					{ "abs",		eMemberType_Abs		},
				};
				map.reserve(ARRAYSIZE(kEntries));
				for(int i = 0; i < ARRAYSIZE(kEntries); ++i)
					map.setValue(kEntries[i].str, kEntries[i].val);
			}
		};
		static NameToEnumMapper sNameToEnumMapper;
		const EMemberType aMemberType =
			sNameToEnumMapper.map.valElse(aParam, eMemberType_Unknown);
		if( aMemberType == eMemberType_Unknown )
		{
			logError("Uknown variable string conversion name '.%s' in '%s'!",
				aParam.c_str(), theTagStr.c_str());
			return varTagToString(result, theTagStr, aPos);
		}
		if( aMemberType < eMemberType_LastCoordType )
		{
			size_t aCoordStrPos = 0;
			const Hotspot::Coord& aCoord = stringToCoord(result, aCoordStrPos);
			if( aCoordStrPos != result.size() )
			{
				logError("Expected an anchor + offset coordinate string "
					"instead of '%s' for conversion type '.%s' in '%s'!",
					result.c_str(), aParam.c_str(), theTagStr.c_str());
				return varTagToString(result, theTagStr, aPos);
			}
			switch(aMemberType)
			{
			case eMemberType_X:
				{
					const u32 aMaxVal = stringToU32(sSectionsMap.vals()
						[kVarsSectionIdx].vals()[kWidthVarID].str);
					const int anAnchorVal =
						u16ToRangeVal(aCoord.anchor, aMaxVal);
					result = toString(clamp(
						anAnchorVal + aCoord.offset, 0, aMaxVal));
					if( theVarDep )
					{// Make sure this recalculates when needed
						theVarDep->varID = kWidthVarID;
						logPropVarDependency(*theVarDep, init);
					}
				}
				break;
			case eMemberType_Y:
				{
					const u32 aMaxVal = stringToU32(sSectionsMap.vals()
						[kVarsSectionIdx].vals()[kHeightVarID].str);
					const int anAnchorVal =
						u16ToRangeVal(aCoord.anchor, aMaxVal);
					result = toString(clamp(
						anAnchorVal + aCoord.offset, 0, aMaxVal));
					if( theVarDep )
					{// Make sure this recalculates when needed
						theVarDep->varID = kHeightVarID;
						logPropVarDependency(*theVarDep, init);
					}
				}
				break;
			case eMemberType_XScaled:
				{
					const u32 aMaxVal = stringToU32(sSectionsMap.vals()
						[kVarsSectionIdx].vals()[kWidthVarID].str);
					const int anAnchorVal =
						u16ToRangeVal(aCoord.anchor, aMaxVal);
					const double aScale = stringToDouble(sSectionsMap.vals()
						[kVarsSectionIdx].vals()[kUIScaleVarID].str);
					result = toString(clamp(
						anAnchorVal + int(aCoord.offset * aScale), 0, aMaxVal));
					if( theVarDep )
					{// Make sure this recalculates when needed
						theVarDep->varID = kWidthVarID;
						logPropVarDependency(*theVarDep, init);
						theVarDep->varID = kUIScaleVarID;
						logPropVarDependency(*theVarDep, init);
					}
				}
				break;
			case eMemberType_YScaled:
				{
					const u32 aMaxVal = stringToU32(sSectionsMap.vals()
						[kVarsSectionIdx].vals()[kHeightVarID].str);
					const int anAnchorVal =
						u16ToRangeVal(aCoord.anchor, aMaxVal);
					const double aScale = stringToDouble(sSectionsMap.vals()
						[kVarsSectionIdx].vals()[kUIScaleVarID].str);
					result = toString(clamp(
						anAnchorVal + int(aCoord.offset * aScale), 0, aMaxVal));
					if( theVarDep )
					{// Make sure this recalculates when needed
						theVarDep->varID = kHeightVarID;
						logPropVarDependency(*theVarDep, init);
						theVarDep->varID = kUIScaleVarID;
						logPropVarDependency(*theVarDep, init);
					}
				}
				break;
			case eMemberType_Offset:
				result = toString(aCoord.offset);
				break;
			case eMemberType_Anchor:
				result = toString(aCoord.anchor / double(0x10000U));
				break;
			}
			return varTagToString(result, theTagStr, aPos);
		}
		else
		{
			size_t aSumStrPos = 0;
			double aSum = stringToDoubleSum(result, aSumStrPos);
			if( aSumStrPos != result.size() )
			{
				logError("Expected string representing a sum of numbers "
					"instead of '%s' for conversion type '.%s' in '%s'!",
					result.c_str(), aParam.c_str(), theTagStr.c_str());
				return varTagToString(result, theTagStr, aPos);
			}

			switch(aMemberType)
			{
			case eMemberType_Sum:
				result = toString(aSum);
				break;
			case eMemberType_Round:
				result = toString(int(floor(aSum+0.5)));
				break;
			case eMemberType_Floor:
				result = toString(int(floor(aSum)));
				break;
			case eMemberType_Ceil:
				result = toString(int(ceil(aSum)));
				break;
			case eMemberType_Abs:
				result = toString(abs(aSum));
				break;
			}
			return varTagToString(result, theTagStr, aPos);
		}
	}

	// Check for valid values (i.e. numbers) for some operators
	double aVarNum = 0, aParamNum = 0;
	if( anOpC != '?' )
	{
		aVarNum = stringToDouble(result, true);
		if( _isnan(aVarNum) && anOpC != '!' && anOpC != '=' )
		{
			if( anOpC == '+' || anOpC == '-' )
			{// Check if a hotspot coord format and can just +/- the offset
				size_t aCoordStrPos = 0;
				stringToCoord(result, aCoordStrPos);
				if( aCoordStrPos == result.size() )
				{// Valid hotspot coord format! Just append operator & param
					result += theTagStr.substr(theFirstOperatorPos, 
						theTagStr.find('}') - theFirstOperatorPos);
					return result;
				}
			}
			logError("Expected a number instead of '%s' for "
				"variable expansion operator in '%s'!",
				result.c_str(), theTagStr.c_str());
			aVarNum = stringToBool(aParam) ? 1.0 : 0;
		}
		aParamNum = stringToDouble(aParam, true);
		if( _isnan(aParamNum) && anOpC != '!' && anOpC != '=' )
		{
			logError("Expected a number instead of '%s' for "
				"variable expansion operator in '%s'. "
				"Note only one operator is allowed per ${} block!",
				aParam.c_str(), theTagStr.c_str());
			aParamNum =
				(anOpC == '+' || anOpC == '-' ) ? 0 :
				(anOpC == '*' || anOpC == '/' || anOpC == '%') ? 1.0 :
				stringToBool(aParam) ? 1.0 : 0;
		}
	}

	// Have all we need for arithmetic operators now
	if( anOpC == '+' || anOpC == '-' ||
		anOpC == '*' || anOpC == '/' || anOpC == '%' )
	{
		if( theTagStr[aPos] != '}' )
		{
			logError("Unexpected %c found in '%s'. "
				"Only one operator is allowed per ${} block! "
				"Use nested ${} blocks for more options.",
				theTagStr[aPos], theTagStr.c_str());
		}
		switch(anOpC)
		{
		case '+': aVarNum += aParamNum; break;
		case '-': aVarNum -= aParamNum; break;
		case '*': aVarNum *= aParamNum; break;
		case '/':
			if( aParamNum == 0 )
			{
				logError("Division by 0 detected in '%s'!",
					theTagStr.c_str());
				aParamNum = 1.0;
			}
			aVarNum /= aParamNum;
			break;
		case '%':
			aParamNum = floor(aParamNum + 0.5);
			if( aParamNum == 0 )
			{
				logError("Division by 0 detected in '%s'!",
					theTagStr.c_str());
				aParamNum = 1.0;
			}
			aVarNum = int(floor(aVarNum + 0.5)) % int(aParamNum);
			break;
		}
		result = toString(aVarNum);
		return result;
	}

	// Math done, should only be comparison or ? operator now
	const bool isTrue = checkVarCompare(
		result, aParam, aVarNum, aParamNum, anOpC);

	// What to do with compare result depends on second operator
	const char anOpC2 = theTagStr[aPos++];
	if( anOpC2 == '}' )
	{
		if( anOpC == '?' )
		{// ${Var ? resultIfTrue}
			result = isTrue ? aParam : "";
			return result;
		}
		// ${Var !<=> value}
		result = isTrue ? "1" : "0";
		return result;
	}

	if( anOpC2 == ':' )
	{// ${Var ? resultIfTrue : resultIfFalse}
		DBG_ASSERT(anOpC == '?');
		if( isTrue )
		{
			result = aParam;
			return result;
		}
		result = fetchNextItem(theTagStr, aPos, "}");
		return result;
	}

	// ${Var !<=> value ? ...} if got this far
	DBG_ASSERT(anOpC2 == '?');

	// Get result for true, or to advance aPos to : for false condition result
	const std::string& aTrueResult = fetchNextItem(theTagStr, aPos, ":}");
	if( isTrue )
		result = aTrueResult;
	else if( theTagStr[aPos++] == ':' )
		result = fetchNextItem(theTagStr, aPos, "}");
	else
		result = "";

	// result is now aTrueResult if condition was true, the section after :
	// if condition was false, or empty if there was no ':' section
	// (${Var !<=> value ? result} format) and condition was false
	return result;
}


static void expandPropertyVars(int theSectionID, int thePropID, bool init)
{
	PropertyMap& theSection = sSectionsMap.vals()[theSectionID];
	Property& theProp = theSection.vals()[thePropID];
	if( !theProp.str.empty() || theProp.pattern.empty() )
		return;

	std::pair<std::string::size_type, std::string::size_type> aTagCoords =
		findStringTag(theProp.pattern, 0, "${", '}');

	if( aTagCoords.first == std::string::npos )
	{// No variables referenced - set .str and clear .pattern via swap
		swap(theProp.str, theProp.pattern);
		return;
	}

	VarPropDependency* aDepPtr = null;
	VarPropDependency aDep;
	aDep.sectID = theSectionID;
	aDep.propID = thePropID;
	PropertyMap& theVarsMap = sSectionsMap.vals()[kVarsSectionIdx];
	DBG_ASSERT(sSectionsMap.keys()[kVarsSectionIdx] == kVariablesSectionName);

	theProp.str = "\b"; // to detect circular reference from recursion
	std::string aStr = theProp.pattern;
	do {
		// Extract variable name (or a number as a const var) from tag
		std::string aRepStr;
		std::string aVarContents;
		const std::string kVarOpChars = "}+-*/?[!~<>=.";
		size_t aVarNameStartPos = aTagCoords.first + 2;
		while(u8(aStr[aVarNameStartPos]) <= ' ')
			++aVarNameStartPos;
		size_t aVarOpPos = aVarNameStartPos;
		bool validVarFound = false;
		if( aStr[aVarNameStartPos] == '-' ||
			aStr[aVarNameStartPos] == '+' ||
			aStr[aVarNameStartPos] == '.' ||
			(aStr[aVarNameStartPos] >= '0' && aStr[aVarNameStartPos] <= '9') )
		{// Possibly a numeric constant in place of an actual variable name
			const double aVarAsNum = stringToDoubleSum(aStr, aVarOpPos);
			if( aVarOpPos > aVarNameStartPos &&
				kVarOpChars.find(aStr[aVarOpPos]) != std::string::npos )
			{
				aVarContents = toString(aVarAsNum);
				validVarFound = true;
			}
		}
		else
		{
			const std::string& aVarName =
				fetchNextItem(aStr, aVarOpPos, kVarOpChars.c_str());
			const int aVarID = theVarsMap.findIndex(aVarName);
			if( aVarID < theVarsMap.size() )
			{
				Property& aVarProp = theVarsMap.vals()[aVarID];
				if( aVarProp.str == "\b" )
				{
					logError("Variable '%s' references self!",
						aVarName.c_str());
				}
				else
				{
					aDepPtr = &aDep;
					aDep.varID = aVarID;
					logPropVarDependency(aDep, init);
					if( aVarProp.str.empty() && !aVarProp.pattern.empty() )
						expandPropertyVars(kVarsSectionIdx, aVarID, init);
					aVarContents = aVarProp.str;
					validVarFound = true;
				}
			}
		}

		DBG_ASSERT(aVarOpPos < aTagCoords.first + aTagCoords.second);
		if( !validVarFound )
		{
			logError("Could not identify variable name from %s in property "
				"[%s] / %s!",
				aStr.substr(aTagCoords.first, aTagCoords.second).c_str(),
				sSectionsMap.keys()[theSectionID].c_str(),
				theSection.keys()[thePropID].c_str());
			expandPropertyVars(theSectionID, thePropID, init);
		}
		else
		{
			aRepStr = varTagToString(
				aVarContents, aStr, aVarOpPos, aDepPtr, init);
		}
		aStr = aStr.replace(aTagCoords.first, aTagCoords.second, aRepStr);
		aTagCoords = findStringTag(aStr, 0, "${", '}');
	} while( aTagCoords.first != std::string::npos );

	theProp.str = aStr;
}


static void readProfileCallback(
	const std::string& theSection,
	const std::string& theName,
	const std::string& theValue,
	void*)
{
	int aSectionID = sSectionsMap.findOrAddIndex(theSection);
	PropertyMap& aSection = sSectionsMap.vals()[aSectionID];
	if( aSectionID == kVarsSectionIdx &&
		(((theName[0] < 'A' || theName[0] > 'Z') &&
		  (theName[0] < 'a' || theName[0] > 'z')) ||
		 (theName.find_first_of("{}+-*/?[:!~<>=.") != std::string::npos)) )
	{
		logError(
			"Variable names must only contain alphanumeric characters "
			"and first character must be A-Z. '%s' is invalid.",
			theName.c_str());
		return;
	}
	Property& aProperty = aSection.findOrAdd(theName);
	aProperty.pattern = theValue;
	aProperty.str.clear();
}


static void propogatePropertyChange(int theSectionID, int thePropertyID)
{
	// Apply variable expansion to this property
	DBG_ASSERT(theSectionID >= 0 && theSectionID < sSectionsMap.size());
	PropertyMap& aSection = sSectionsMap.vals()[theSectionID];
	DBG_ASSERT(thePropertyID >= 0 && thePropertyID < aSection.size());
	Property& aProp = aSection.vals()[thePropertyID];
	if( !aProp.pattern.empty() )
	{
		aProp.str.clear();
		expandPropertyVars(theSectionID, thePropertyID, false);
	}

	if( theSectionID == kVarsSectionIdx )
	{// Property is a variable - update other properties that depend on it
		VarPropDependency aSearchVarDep;
		aSearchVarDep.varID = thePropertyID;
		for(std::vector<VarPropDependency>::const_iterator itr =
				std::lower_bound(
					sVarPropDepList.begin(),
					sVarPropDepList.end(),
					aSearchVarDep);
			itr != sVarPropDepList.end() && int(itr->varID) == thePropertyID;
			++itr)
		{
			propogatePropertyChange(itr->sectID, itr->propID);
		}
	}
	else
	{// Log property update in sChangedSectionsMap for other modules as well
		sChangedSectionsMap.findOrAdd(sSectionsMap.keys()[theSectionID])
			.setValue(aSection.keys()[thePropertyID], aProp);
	}
}


static void setPropertyAfterLoad(
	int theSectionID,
	int thePropertyID,
	const std::string& theValue,
	bool saveToFile)
{
	DBG_ASSERT(theSectionID >= 0 && theSectionID < sSectionsMap.size());

	PropertyMap& aSection = sSectionsMap.vals()[theSectionID];
	DBG_ASSERT(thePropertyID >= 0 && thePropertyID < aSection.size());
	Property& aProp = aSection.vals()[thePropertyID];

	const bool saveToMap = aProp.pattern.empty()
		? (aProp.str != theValue) : (aProp.pattern != theValue);
	saveToFile = saveToFile &&
		(aProp.file.empty() ? saveToMap : aProp.file != theValue);

	// If a temporary change, make a backup of original file string so that
	// if try re-applying the same value later but with saveToFile as true,
	// can detect need to save even though active map won't be updated.
	// Alternatively, if have a backup and below will set active value back
	// to matching what is saved to file, then no longer need the backup.
	if( saveToMap && !saveToFile )
	{
		if( aProp.file.empty() )
			swap(aProp.file, aProp.pattern.empty() ? aProp.str : aProp.pattern);
		else if( aProp.file == theValue )
			aProp.file.clear();
	}

	if( saveToMap )
	{
		// Set pattern string (at least temporarily - below may clear it)
		aProp.pattern = theValue;

		// Apply variable expansion (or just move from .pattern to .str),
		// if a variable property propogate it to other properties,
		// and log in changes map so outside modules are informed of change
		propogatePropertyChange(theSectionID, thePropertyID);
	}

	if( saveToFile )
	{// Log as change to save to file
		for(int i = 0, end = intSize(sUnsavedChangesList.size()); i < end; ++i)
		{
			if( sUnsavedChangesList[i].sectionID == theSectionID &&
				sUnsavedChangesList[i].propertyID == thePropertyID )
			{
				sUnsavedChangesList[i].value = theValue;
				return;
			}
		}

		sUnsavedChangesList.push_back(UnsavedProperty());
		sUnsavedChangesList.back().sectionID = theSectionID;
		sUnsavedChangesList.back().propertyID = thePropertyID;
		sUnsavedChangesList.back().value = theValue;

		// File data will now match active map data, so can set .file to be
		// the same as .pattern or .str, but .file.empty() means the same thing
		aProp.file.clear();
	}
}


static void linkParentProfiles()
{
	// NOTE: sProfiles.size() can grow during this, so must be checked each loop
	for(int i = 1; i < intSize(sProfiles.size()); ++i)
	{
		// Make a copy in case sProfiles gets invalidated during callback
		const std::string aPath = sProfiles.vals()[i].path;
		if( fileExists(aPath) )
			parseINI(addParentCallback, aPath, eParseMode_Header, &i);
	}
}


static void syncProfileDisplayList()
{
	// Clear any previous parent data
	for(int i = 1, end = sProfiles.size(); i < end; ++i)
	{
		sProfiles.vals()[i].isAParent = false;
		sProfiles.vals()[i].parent.clear();
	}

	// Scan folder for all profile .ini files
	WIN32_FIND_DATA aFindData;
	const std::wstring& aSearchPattern =
		widen(iniFolderPath()) +
		widen(kProfileFileNamePrefix) + L'*' +
		widen(kProfileFileNameSuffix);
	HANDLE hFind = FindFirstFile(aSearchPattern.c_str(), &aFindData);
	if( hFind != INVALID_HANDLE_VALUE )
	{
		do {
			if( !(aFindData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) )
			{
				const std::string& aFileName = narrow(aFindData.cFileName);
				const int aProfileID =
					sProfiles.findOrAddIndex(extractProfileName(aFileName));
				if( aProfileID == 0 )
					continue;
				sProfiles.vals()[aProfileID].path = iniFolderPath() + aFileName;
			}
		} while(FindNextFile(hFind, &aFindData));
	}
	FindClose(hFind);
	sPerformedProfileFolderScan = true;

	// Link profiles to parents (may generate new parents!)
	linkParentProfiles();

	// Generate a new list but attempting to maintain previous list order by
	// first adding any valid entries from the old list to a StringToValueMap,
	// which stores keys in order added but eliminates duplicates.
	StringToValueMap<int> aNewDisplayList;
	aNewDisplayList.reserve(intSize(sDisplayedProfileList.size()));
	for(int i = 0, end = intSize(sDisplayedProfileList.size()); i < end; ++i)
	{
		if( sDisplayedProfileList[i].empty() )
			continue;
		if( ProfileData* aProfile = sProfiles.find(sDisplayedProfileList[i]) )
		{
			if( !aProfile->isAParent && fileExists(aProfile->path) )
				aNewDisplayList.findOrAdd(sDisplayedProfileList[i]);
		}
	}
	// Now add any valid entries that are missing from the old list
	for(int i = 1, end = intSize(sProfiles.size()); i < end; ++i)
	{
		if( sProfiles.vals()[i].isAParent )
			continue;
		if( !fileExists(sProfiles.vals()[i].path) )
			continue;
		aNewDisplayList.findOrAdd(sProfiles.keys()[i]);
	}

	// Transfer aNewDisplayList.keys() to sDisplayedProfileList, recording any
	// that are different in Core .ini file as go through them.
	// Do not shrink displayed list yet so can write out blank entries to Core,
	// but make sure it is at least as large as new list is now.
	if( sDisplayedProfileList.size() < size_t(aNewDisplayList.size()) )
		sDisplayedProfileList.resize(aNewDisplayList.size());
	for(int i = 0, end = intSize(sDisplayedProfileList.size()); i < end; ++i)
	{
		const std::string& aProfileName =
			i < aNewDisplayList.size()
				? aNewDisplayList.keys()[i]
				: std::string();
		if( sDisplayedProfileList[i] != aProfileName )
		{
			sDisplayedProfileList[i] = aProfileName;
			setPropertyInINI(
				sProfiles.vals()[0].path, "",
				std::string(kProfileKeyPrefix) + toString(i+1),
				aProfileName);
		}
	}
	sDisplayedProfileList.resize(aNewDisplayList.size());
}


static void loadCoreProfile()
{
	// Start with a fresh map
	sSectionsMap.clear();
	confirmSafeToWriteToMap();
	// Make sure "variables" section is always section 0
	sSectionsMap.setValue(kVariablesSectionName, PropertyMap());
	sVarPropDepList.clear();
	// Add built-in system variables to variables section
	PropertyMap& aVarMap = sSectionsMap.vals()[kVarsSectionIdx];
	Property aProp;
	aProp.str = "1.0"; aVarMap.setValue(kUIScaleVarName, aProp);
	aProp.str = "1920"; aVarMap.setValue(kWidthVarName, aProp);
	aProp.str = "1080"; aVarMap.setValue(kHeightVarName, aProp);
	aProp.str = "false"; aVarMap.setValue(kLinuxVarName, aProp);
	aProp.str = "Yes"; aVarMap.setValue(kCopyIconsVarName, aProp);
	aProp.str = "Yes"; aVarMap.setValue(kCopyExcludeOverlaysVarName, aProp);
	aProp.str = ".\\"; aVarMap.setValue("TargetAppDir", aProp);
	aProp.str = toString(GetSystemMetrics(SM_CXSCREEN));
	aVarMap.setValue("LastGameWindowWidth", aProp);
	aProp.str = toString(GetSystemMetrics(SM_CYSCREEN));
	aVarMap.setValue("LastGameWindowHeight", aProp);
	DBG_ASSERT(sSectionsMap.keys()[kVarsSectionIdx] == kVariablesSectionName);
	DBG_ASSERT(aVarMap.keys()[kUIScaleVarID] == kUIScaleVarName);
	DBG_ASSERT(aVarMap.keys()[kWidthVarID] == kWidthVarName);
	DBG_ASSERT(aVarMap.keys()[kHeightVarID] == kHeightVarName);

	DBG_ASSERT(!sProfiles.empty());
	if( !fileExists(sProfiles.vals()[0].path) )
	{
		logFatalError(
			"Could not find required Core profile %s",
			sProfiles.vals()[0].path.c_str());
		return;
	}
	checkForOutdatedFileVersion(sProfiles.vals()[0].path);
	parseINI(
		readProfileCallback,
		sProfiles.vals()[0].path,
		eParseMode_Sections);
}


static void loadProfileWithParentFirst(const ProfileData& theProfile)
{
	if( !theProfile.parent.empty() )
	{
		loadProfileWithParentFirst(sProfiles.quickFind(theProfile.parent));
		if( hadFatalError() )
			return;
	}

	if( !fileExists(theProfile.path) )
	{
		Dialogs::showError(strFormat(
			"Could not find expected profile file: %s",
			theProfile.path.c_str()));
		return;
	}

	checkForOutdatedFileVersion(theProfile.path);
	parseINI(
		readProfileCallback,
		theProfile.path,
		eParseMode_Sections);
}


static int queryUserForProfileImpl(int& theLastSelectedProfileIdx)
{
	int result = 0;
	DBG_ASSERT(!sProfiles.empty());
	if( hadFatalError() )
		return result;

	// Create lists needed for dialog
	enum EType
	{
		eType_CopyFile,			// index into sKnownFiles
		eType_CopyResCustom,	// index into kResTemplateCustom
		eType_ParentResBase,	// index into kResTemplateBase
		eType_ParentResDefault,	// index into kResTemplateDefault
		eType_ParentFile,		// index into sKnownFiles
	};
	std::vector<std::string> aTemplateProfileNames;
	std::vector<int> aTemplateRelativeIndexes;
	std::vector<EType> aTemplateProfileType;
	const std::string kCopyFilePrefix = "Copy \"";
	const std::string kParentPrefix = "Customize \"";

	for(int i = 0, end = intSize(sDisplayedProfileList.size()); i < end; ++i)
	{
		aTemplateProfileNames.push_back(
			kCopyFilePrefix + sDisplayedProfileList[i] + '"');
		aTemplateRelativeIndexes.push_back(i);
		aTemplateProfileType.push_back(eType_CopyFile);
	}

	const bool needFirstProfile = sDisplayedProfileList.empty();
	for(int i = 0; i < ARRAYSIZE(kResTemplateCustom); ++i)
	{
		if( needFirstProfile )
			sDisplayedProfileList.push_back(kResTemplateCustom[i].dispName);
		aTemplateProfileNames.push_back(
			kCopyFilePrefix + kResTemplateCustom[i].dispName + '"');
		aTemplateRelativeIndexes.push_back(i);
		aTemplateProfileType.push_back(eType_CopyResCustom);
	}

	for(int i = 0, end = intSize(sProfiles.size()); i < end; ++i)
	{
		aTemplateProfileNames.push_back(
			kParentPrefix + sProfiles.keys()[i] + '"');
		aTemplateRelativeIndexes.push_back(i);
		aTemplateProfileType.push_back(eType_ParentFile);
	}

	for(int i = 0; i < ARRAYSIZE(kResTemplateBase); ++i)
	{
		if( sProfiles.contains(kResTemplateBase[i].fileName) )
			continue;
		aTemplateProfileNames.push_back(
			kParentPrefix + kResTemplateBase[i].dispName + '"');
		aTemplateRelativeIndexes.push_back(i);
		aTemplateProfileType.push_back(eType_ParentResBase);
	}

	for(int i = 0; i < ARRAYSIZE(kResTemplateDefault); ++i)
	{
		if( sProfiles.contains(kResTemplateBase[i].fileName) )
			continue;
		aTemplateProfileNames.push_back(
			kParentPrefix + kResTemplateDefault[i].dispName + '"');
		aTemplateRelativeIndexes.push_back(i);
		aTemplateProfileType.push_back(eType_ParentResDefault);
	}
	DBG_ASSERT(aTemplateRelativeIndexes.size() == aTemplateProfileNames.size());
	DBG_ASSERT(aTemplateProfileType.size() == aTemplateProfileNames.size());

	// Use Dialog to ask the user what they want to do
	int aLoadedProfileDisplayIdx = -1;
	if( sLoadedProfileIdx > 0 )
	{
		const std::string& aLoadedProfileName =
			sProfiles.keys()[sLoadedProfileIdx];
		for(int i = 0, end = intSize(sDisplayedProfileList.size());
			i < end; ++i)
		{
			if( sDisplayedProfileList[i] == aLoadedProfileName )
				aLoadedProfileDisplayIdx = i;
		}
	}
	int aDefaultSelectedIdx =
		theLastSelectedProfileIdx >= 0
			? theLastSelectedProfileIdx
			: aLoadedProfileDisplayIdx;
	Dialogs::ProfileSelectResult aDialogResult = Dialogs::profileSelect(
		sDisplayedProfileList,
		aTemplateProfileNames,
		aDefaultSelectedIdx,
		aLoadedProfileDisplayIdx,
		sAutoLoadProfileIdx > 0,
		needFirstProfile);

	// Regardless of whatever else chose, if un-checked AutoLoad then remember
	if( !aDialogResult.autoLoadRequested )
		setAutoLoadProfile(0);

	// Regardless of whatever else chose, save changes to display list order
	if( aDialogResult.orderChanged )
	{
		for(int i = 0, end = intSize(sDisplayedProfileList.size());
			i < end; ++i)
		{
			setPropertyInINI(
				sProfiles.vals()[0].path, "",
				std::string(kProfileKeyPrefix) + toString(i+1),
				sDisplayedProfileList[i]);
		}
	}

	if( aDialogResult.cancelled )
	{// User declined to select anything
		return result; // 0
	}

	// For first profile, if no name given then use built-in name
	// NOTE: This only works out because set the first entries of
	// aTemplateProfile's to match aLoadableProfile's which both
	// match the entries in kResTemplateCustom. So need to change
	// this if rearrange the order of any of these above!
	if( needFirstProfile && aDialogResult.newName.empty() )
	{
		aDialogResult.newName =
			kResTemplateCustom[aDialogResult.selectedIndex].fileName;
	}

	if( aDialogResult.newName.empty() )
	{// User must have requested to load/edit/delete an existing profile
		DBG_ASSERT(size_t(aDialogResult.selectedIndex) <
			sDisplayedProfileList.size());
		theLastSelectedProfileIdx = aDialogResult.selectedIndex;
		result = sProfiles.quickFindIndex(
			sDisplayedProfileList[aDialogResult.selectedIndex]);
		if( aDialogResult.editProfileRequested )
		{
			userEditProfile(result, false);
			syncProfileDisplayList();
			result = -1; // repeat query from the start
		}
		else if( aDialogResult.deleteProfileRequested )
		{
			const std::string& aProfName =
				sDisplayedProfileList[aDialogResult.selectedIndex];
			if( ProfileData* aProfile = sProfiles.find(aProfName) )
			{
				if( Dialogs::yesNoPrompt(strFormat(
						"Are you sure you wish to delete '%s'?\n\n"
						"NOTE: This will NOT automatically delete any parent " 
						"profiles of '%s'.",
						aProfile->path.c_str(),
						aProfName.c_str()),
						"Delete Profile") == eResult_Yes )
				{
					DeleteFile(widen(aProfile->path.c_str()).c_str());
					theLastSelectedProfileIdx = -1;
				}
			}
			syncProfileDisplayList();
			result = -1; // repeat query from the start
		}
		else if( aDialogResult.autoLoadRequested )
		{
			setAutoLoadProfile(result);
		}
		return result;
	}

	// User must have requested creating a new profile
	const std::string& aNewName = extractProfileName(aDialogResult.newName);
	const std::string& aNewPath = profileNameToFilePath(aNewName);

	if( fileExists(aNewPath) )
	{// File already exists
		if( isSamePath(aNewPath, sProfiles.vals()[0].path) )
		{
			Dialogs::showError(strFormat(
				"Can not create custom Profile with the name %s!",
				sProfiles.keys()[0].c_str()));
			result = -1; // repeat query from the start
			return result;
		}
		int aDupProfileIdx = sProfiles.findIndex(aNewName);
		if( aDupProfileIdx >= sProfiles.size() ||
			sProfiles.vals()[aDupProfileIdx].isAParent )
		{
			Dialogs::showError(strFormat(
				"File '%s' already exists and does not allow overwrite "
				"(likely acting as parent to another profile).",
				getFileName(aNewPath).c_str()));
			result = -1; // repeat query from the start
			return result;
		}
		if( Dialogs::yesNoPrompt(strFormat(
				"Profile '%s' already exists. Overwrite?",
					aNewName.c_str()),
				"Overwrite existing Profile") != eResult_Yes )
		{
			result = -1; // repeat query from the start
			return result;
		}
		sProfiles.vals()[aDupProfileIdx].parent.clear();
	}

	int aSrcIdx = aDialogResult.selectedIndex;
	DBG_ASSERT(size_t(aSrcIdx) < aTemplateProfileType.size());
	EType aProfileType = aTemplateProfileType[aDialogResult.selectedIndex];
	if( aProfileType == eType_ParentResDefault ||
		aProfileType == eType_CopyResCustom )
	{// Do not allow Base profile names for a new profile of these types
		// This is to prevent possibly having self as grandparent
		const std::string& aCompName = condense(aNewName);
		for(int i = 0; i < ARRAYSIZE(kResTemplateBase); ++i)
		{
			if( aCompName == condense(kResTemplateBase[i].fileName) )
			{
				Dialogs::showError(
					"Selected Profile name not valid (reserved)!");
				result = -1; // repeat query from the start
				return result;
			}
		}
	}

	if( aProfileType == eType_CopyResCustom )
	{// Do not allow Default profile names for a new profile of these types
		// This is to prevent possibly having self as a parent
		const std::string& aCompName = condense(aNewName);
		for(int i = 0; i < ARRAYSIZE(kResTemplateDefault); ++i)
		{
			if( aCompName == condense(kResTemplateDefault[i].fileName) )
			{
				Dialogs::showError(
					"Selected Profile name not valid (reserved)!");
				result = -1; // repeat query from the start
				return result;
			}
		}
	}

	// Add new entry to sProfiles and use index as possible return value
	result = sProfiles.findOrAddIndex(aNewName);
	sProfiles.vals()[result].path = aNewPath;
	DBG_ASSERT(result > 0);

	switch(aProfileType)
	{
	case eType_CopyFile:
		{// Create copy of source file
			const ProfileData& aSrcProfile = sProfiles.quickFind(
				sDisplayedProfileList[aTemplateRelativeIndexes[aSrcIdx]]);
			// Don't actually do anything if source and dest are the same file
			if( !isSamePath(aNewPath, aSrcProfile.path) )
			{
				CopyFile(
					widen(aSrcProfile.path).c_str(),
					widen(aNewPath).c_str(),
					FALSE);
			}
		}
		break;
	case eType_CopyResCustom:
		{// Generate resource profile but with new file name
			const int aResTemplateIdx = aTemplateRelativeIndexes[aSrcIdx];
			DBG_ASSERT(aResTemplateIdx >= 0);
			DBG_ASSERT(aResTemplateIdx < ARRAYSIZE(kResTemplateCustom));
			ResourceFile aResFile = kResTemplateCustom[aResTemplateIdx];
			aResFile.fileName = aNewName.c_str();
			generateResourceFile(aResFile);
		}
		break;
	case eType_ParentResBase:
	case eType_ParentResDefault:
		{// Generate resource profile to act as parent
			const int aResBaseIdx = aTemplateRelativeIndexes[aSrcIdx];
			const char* aProfileName = null;
			if( aProfileType == eType_ParentResBase )
			{
				DBG_ASSERT(aResBaseIdx < ARRAYSIZE(kResTemplateBase));
				generateResourceFile(kResTemplateBase[aResBaseIdx]);
				aProfileName = kResTemplateBase[aResBaseIdx].fileName;
			}
			else
			{
				DBG_ASSERT(aResBaseIdx < ARRAYSIZE(kResTemplateDefault));
				generateResourceFile(kResTemplateDefault[aResBaseIdx]);
				aProfileName = kResTemplateDefault[aResBaseIdx].fileName;
			}
			const int aProfileID = sProfiles.findOrAddIndex(aProfileName);
			sProfiles.vals()[aProfileID].path =
				profileNameToFilePath(aProfileName);
			if( aProfileType == eType_ParentResBase )
				sNewBaseProfileIdx = aProfileID;
			// Treat as _ParentFile type now that resource exists as a file
			aTemplateProfileNames.push_back("");
			aTemplateRelativeIndexes.push_back(aProfileID);
			aTemplateProfileType.push_back(eType_ParentFile);
			aSrcIdx = intSize(aTemplateProfileType.size()) - 1;
		}
		// fall through
	case eType_ParentFile:
		{// Create new file that sets source file as its parent profile
			const int aParentProfileIdx = aTemplateRelativeIndexes[aSrcIdx];
			DBG_ASSERT(aParentProfileIdx < sProfiles.size());
			// Make sure parent and new file are not the same file
			if( isSamePath(sProfiles.vals()[aParentProfileIdx].path, aNewPath) )
			{
				Dialogs::showError(
					"Selected Profile name matches parent profile name!");
				result = -1; // repeat query from the start
				return result;
			}
			ResourceFile aResFile = kResTemplateBlank;
			aResFile.fileName = aNewName.c_str();
			generateResourceFile(aResFile);
			// Specify parent profile (unless it is Core/0)
			if( aParentProfileIdx > 0 )
			{
				setPropertyInINI(
					aNewPath, "",
					"ParentProfile", sProfiles.keys()[aParentProfileIdx]);
			}
		}
		break;
	}

	if( !fileExists(aNewPath) )
	{
		Dialogs::showError(strFormat(
			"Failure creating new Profile '%s' (%s)!",
			aNewName.c_str(), aNewPath.c_str()));
		result = -1; // repeat query from the start
		return result;
	}

	// Add new profile to display list
	if( needFirstProfile )
		sDisplayedProfileList.clear();
	syncProfileDisplayList();
	theLastSelectedProfileIdx = intSize(sDisplayedProfileList.size())-1;

	// Extra prompts for first time create a "base" profile, which represents
	// the shared default values for all profiles for a particular game, and
	// thus need to set some of these default but game-specific settings
	if( sNewBaseProfileIdx >= 0 )
	{
		// Make sure core has been loaded to get needed variable values
		// (such as alternate suggested launch params in Linux)
		if( sSectionsMap.empty() )
			loadCoreProfile();

		// Load defaults values from generated file
		const BaseGameSettings& aDefaultSettings =
			getBaseGameSettings(sProfiles.vals()[sNewBaseProfileIdx].path);
		BaseGameSettings aSettings = aDefaultSettings;

		// Prompt user for auto-launch configuration
		aSettings.autoLaunchAppPath =
			expandVars(aSettings.autoLaunchAppPath);
		aSettings.autoLaunchAppParams =
			expandVars(aSettings.autoLaunchAppParams);
		aSettings.autoQuitWithTargetApp =
			expandVars(aSettings.autoQuitWithTargetApp);
		// Don't ask about auto-launching an app when already have one active
		if( TargetApp::targetAppActive() )
		{
			aSettings.autoLaunchAppPath.clear();
		}
		else if( Dialogs::yesNoPrompt(
				"Would you like to automatically launch target game's "
				"launcher/patcher when loading this profile at startup?",
				"Auto-Launch Target App") == eResult_Yes )
		{
			Dialogs::targetAppPath(
				aSettings.autoLaunchAppPath,
				aSettings.autoLaunchAppParams,
				aSettings.autoQuitWithTargetApp);
		}
		else
		{
			aSettings.autoLaunchAppPath.clear();
		}

		writeBaseGameSettingsChanges(
			sProfiles.vals()[sNewBaseProfileIdx].path,
			aDefaultSettings,
			aSettings);

		// Load read-in known issues key now, before rest of profile,
		// so can generate it and display it immediately
		generateKnownIssuesRTF(aDefaultSettings.knownIssuesList);
		if( sNeedShowKnownIssues )
		{
			Dialogs::showKnownIssues();
			sNeedShowKnownIssues = false;
		}
	}
	sNewBaseProfileIdx = -1;

	if( needFirstProfile )
	{
		if( Dialogs::yesNoPrompt(
				"Would you like to edit this Profile now to match your in-game "
				"Key Binds and other settings?",
				"Edit new profile") == eResult_Yes )
		{
			userEditProfile(result, true);
		}
		else
		{
			return result;
		}
	}

	// Query again to actually load the new profile
	result = -1;
	return result;
}


static int queryUserForProfileID()
{
	saveChangesToFile();
	if( !sPerformedProfileFolderScan )
		syncProfileDisplayList();
	int aLastCreatedProfileIdx = -1;
	int result = -1;
	while(result < 0)
		result = queryUserForProfileImpl(aLastCreatedProfileIdx);
	return result;
}


//------------------------------------------------------------------------------
// Global Functions
//------------------------------------------------------------------------------

void init()
{
	DBG_ASSERT(sProfiles.empty());
	// Check for core profile directly and make sure it is set as index 0
	ProfileData& aCoreProfile = sProfiles.findOrAdd(kResTemplateCore.fileName);
	aCoreProfile.path = profileNameToFilePath(kResTemplateCore.fileName);
	aCoreProfile.isAParent = true;
	if( !fileExists(sProfiles.vals()[0].path) )
	{// Core .ini file not found!
		// Assume this means first run, which means show license agreement
		if( Dialogs::showLicenseAgreement() == eResult_Declined )
		{// Declined license agreement - just exit
			gShutdown = true;
		}
		else
		{// Generate Core.ini which will prevent future license agreement
			generateResourceFile(kResTemplateCore);
			if( !fileExists(aCoreProfile.path) )
			{
				logFatalError("Unable to find/write %s (%s)",
					kResTemplateCore.fileName, aCoreProfile.path.c_str());
			}
			else
			{
				addSystemCheckVarsToProfile(aCoreProfile.path);
			}
		}
	}

	if( gShutdown || hadFatalError() )
		return;

	// Read core profile's header to get profile auto-load and display order
	sAutoLoadProfileIdx = 0;
	gProfileToLoad.clear();
	sDisplayedProfileList.clear();
	parseINI(
		getProfileListCallback,
		aCoreProfile.path,
		eParseMode_Header);

	if( isAnInteger(gProfileToLoad) )
	{
		// Likely using older system of specifying number from display list
		// Convert to actual direct name of the profile pulled from the list 
		const int anInt = stringToInt(gProfileToLoad) - 1;
		if( anInt >= 0 && size_t(anInt) < sDisplayedProfileList.size() )
			gProfileToLoad = sDisplayedProfileList[anInt];
	}
	
	if( !gProfileToLoad.empty() )
	{// Has requested auto-load, so only worry about that profile
		sAutoLoadProfileIdx = sProfiles.findOrAddIndex(gProfileToLoad);
		ProfileData& aProfile = sProfiles.vals()[sAutoLoadProfileIdx];
		// Try path with name as-is, and then with spaces replaced by '_'
		aProfile.path = profileNameToFilePath(gProfileToLoad, false);
		if( !fileExists(aProfile.path) )
			aProfile.path = profileNameToFilePath(gProfileToLoad, true);
		if( fileExists(aProfile.path) )
		{
			linkParentProfiles();
			return;
		}
	}

	// Search for and fix discrepencies between actual files and list in Core
	syncProfileDisplayList();
	
	// Query which profile to load (or create one)
	gProfileToLoad = queryUserForProfile();
}


void load()
{
	const int aProfileIDToLoad =
		gProfileToLoad.empty()
			? sLoadedProfileIdx
			: sProfiles.findIndex(gProfileToLoad);
	if( aProfileIDToLoad == 0 || aProfileIDToLoad >= sProfiles.size() )
	{
		logFatalError("Requested to load unknown profile name '%s'",
			gProfileToLoad.c_str());
		return;
	}

	logInfo("Loading profile '%s'", sProfiles.keys()[aProfileIDToLoad].c_str());

	// Prepare for reading known issues
	sNeedShowKnownIssues = false;
	sKnownIssuesRTF.clear();

	// Always load the core first as the automatic ultimate parent profile
	loadCoreProfile();
	if( hadFatalError() )
		return;

	// Use a bit of recursion to load profiles in reverse order (parents first)
	loadProfileWithParentFirst(sProfiles.vals()[aProfileIDToLoad]);
	if( hadFatalError() )
		return;
	sSectionsMap.trim();

	// Process variable expansion for all properties
	for(int aSectionID = 0; aSectionID < sSectionsMap.size(); ++aSectionID)
	{
		PropertyMap& aSection = sSectionsMap.vals()[aSectionID];
		for(int aPropID = 0; aPropID < aSection.size(); ++aPropID)
			expandPropertyVars(aSectionID, aPropID, true);
	}

	// Sort and remove duplicate entries in variable dependency list
	std::sort(sVarPropDepList.begin(), sVarPropDepList.end());
	sVarPropDepList.erase(
		std::unique(sVarPropDepList.begin(), sVarPropDepList.end()),
		sVarPropDepList.end());

	// Set up values for a profile having been loaded properly
	sLoadedProfileIdx = aProfileIDToLoad;
	sNewBaseProfileIdx = -1;
	gProfileToLoad.clear();
}


std::string queryUserForProfile()
{
	int aProfileID = queryUserForProfileID();
	if( aProfileID > 0 && aProfileID < sProfiles.size() )
		return sProfiles.keys()[aProfileID];
	return std::string();
}


std::string userEditCurrentProfile()
{
	saveChangesToFile();
	if( userEditProfile(sLoadedProfileIdx, false) )
		return sProfiles.keys()[sLoadedProfileIdx];

	return std::string();
}


const std::string& getKnownIssuesRTF()
{
	if( sKnownIssuesRTF.empty() )
	{
		generateKnownIssuesRTF(getStr(
			kBaseGameSettingsSection, kKnownIssuesKey));
	}
	sNeedShowKnownIssues = false;
	return sKnownIssuesRTF;
}


std::string getStr(
	const std::string& theSection,
	const std::string& thePropertyName,
	const std::string& theDefaultValue)
{
	if( const PropertyMap* aSection = sSectionsMap.find(theSection) )
	{
		if( const Property* aProp = aSection->find(thePropertyName) )
		{
			if( !aProp->str.empty() )
				return aProp->str;
		}
	}

	return theDefaultValue;
}


int getInt(
	const std::string& theSection,
	const std::string& theName,
	int theDefaultValue)
{
	const std::string& aStr = getStr(theSection, theName);
	if( !aStr.empty() )
		return stringToInt(aStr);
	return theDefaultValue;
}


bool getBool(
	const std::string& theSection,
	const std::string& theName,
	bool theDefaultValue)
{
	const std::string& aStr = getStr(theSection, theName);
	if( !aStr.empty() )
		return stringToBool(aStr);
	return theDefaultValue;
}


double getFloat(
	const std::string& theSection,
	const std::string& theName,
	double theDefaultValue)
{
	const std::string& aStr = getStr(theSection, theName);
	if( !aStr.empty() )
		return stringToDouble(aStr);
	return theDefaultValue;
}


int variableNameToID(const std::string& theVarName)
{
	int result = sSectionsMap.vals()[kVarsSectionIdx].findIndex(theVarName);
	if( result >= sSectionsMap.vals()[kVarsSectionIdx].size() )
		result = -1;
	return result;
}


std::string variableIDToName(int theVariableID)
{
	DBG_ASSERT(theVariableID >= 0);
	DBG_ASSERT(theVariableID < sSectionsMap.vals()[kVarsSectionIdx].size());
	return sSectionsMap.vals()[kVarsSectionIdx].keys()[theVariableID];
}


std::string getVariable(int theVariableID)
{
	DBG_ASSERT(theVariableID >= 0);
	DBG_ASSERT(theVariableID < sSectionsMap.vals()[kVarsSectionIdx].size());
	return sSectionsMap.vals()[kVarsSectionIdx].vals()[theVariableID].str;
}


std::string getVariable(const std::string& theVarName)
{
	return getStr(getSectionProperties(kVarsSectionIdx), theVarName);
}


std::string expandVars(std::string theString)
{
	std::string result;
	PropertyMap& theVarsMap = sSectionsMap.vals()[kVarsSectionIdx];
	std::pair<std::string::size_type, std::string::size_type> aTagCoords =
		findStringTag(theString, 0, "${", '}');

	while( aTagCoords.first != std::string::npos )
	{
		// Extract variable name from tag
		size_t aVarOpPos = aTagCoords.first + 2;
		const std::string& aVarName =
			fetchNextItem(theString, aVarOpPos, "}+-*/?[!~<>=.");
		const int aVarID = theVarsMap.findIndex(aVarName);
		if( aVarOpPos < aTagCoords.first + aTagCoords.second &&
			!aVarName.empty() && aVarID < theVarsMap.size() )
		{
			if( theVarsMap.vals()[aVarID].str.empty() )
				expandPropertyVars(kVarsSectionIdx, aVarID, false);
			const std::string& aRepStr = varTagToString(
				theVarsMap.vals()[aVarID].str,
				theString, aVarOpPos);
			theString = theString.replace(
				aTagCoords.first, aTagCoords.second, aRepStr);
			aTagCoords = findStringTag(theString, 0, "${", '}');
		}
		else
		{
			return theString;
		}
	}

	return theString;
}


int getSectionID(const std::string& theSectionName)
{
	int result = sSectionsMap.findIndex(theSectionName);
	if( result >= sSectionsMap.size() )
		result = -1;
	return result;
}


PropertyMapPtr getSectionProperties(const std::string& theSectionName)
{
	return getSectionProperties(getSectionID(theSectionName));
}


PropertyMapPtr getSectionProperties(int theSectionID)
{
	static const PropertyMap kEmptyMap = PropertyMap();
	if( theSectionID >= 0 && theSectionID < sSectionsMap.size() )
		return &sSectionsMap.vals()[theSectionID];
	return &kEmptyMap;
}


const SectionsMap& allSections()
{
	return sSectionsMap;
}


std::string getStr(
	PropertyMapPtr theSection,
	const std::string& thePropertyName,
	const std::string& theDefaultValue)
{
	if( const Property* aProp = theSection->find(thePropertyName) )
	{
		if( !aProp->str.empty() )
			return aProp->str;
	}

	return theDefaultValue;
}


int getInt(
	PropertyMapPtr theSection,
	const std::string& theName,
	int theDefaultValue)
{
	const std::string& aStr = getStr(theSection, theName);
	if( !aStr.empty() )
		return stringToInt(aStr);
	return theDefaultValue;
}


bool getBool(
	PropertyMapPtr theSection,
	const std::string& theName,
	bool theDefaultValue)
{
	const std::string& aStr = getStr(theSection, theName);
	if( !aStr.empty() )
		return stringToBool(aStr);
	return theDefaultValue;
}


double getFloat(
	PropertyMapPtr theSection,
	const std::string& theName,
	double theDefaultValue)
{
	const std::string& aStr = getStr(theSection, theName);
	if( !aStr.empty() )
		return stringToDouble(aStr);
	return theDefaultValue;
}


void setStr(
	const std::string& theSection,
	const std::string& thePropertyName,
	const std::string& theValue,
	bool saveToFile)
{
	confirmSafeToWriteToMap();
	const int aSectionID = sSectionsMap.findOrAddIndex(theSection);
	PropertyMap& aSection = sSectionsMap.vals()[aSectionID];
	const int aPropID = aSection.findOrAddIndex(thePropertyName);
	setPropertyAfterLoad(aSectionID, aPropID, theValue, saveToFile);
}


void setStr(
	int theSectionID,
	const std::string& thePropertyName,
	const std::string& theValue,
	bool saveToFile)
{
	confirmSafeToWriteToMap();
	DBG_ASSERT(theSectionID >= 0 && theSectionID < sSectionsMap.size());
	PropertyMap& aSection = sSectionsMap.vals()[theSectionID];
	const int aPropID = aSection.findOrAddIndex(thePropertyName);
	setPropertyAfterLoad(theSectionID, aPropID, theValue, saveToFile);
}


void setVariable(int theVarID, const std::string& theValue, bool temporary)
{
	confirmSafeToWriteToMap();
	setPropertyAfterLoad(kVarsSectionIdx, theVarID, theValue, !temporary);
}


void setVariable(
	const std::string& theVarName,
	const std::string& theValue,
	bool temporary)
{
	confirmSafeToWriteToMap();
	const int theVarID =
		sSectionsMap.vals()[kVarsSectionIdx].findOrAddIndex(theVarName);
	setPropertyAfterLoad(kVarsSectionIdx, theVarID, theValue, !temporary);
}


void reloadVariable(int theVarID)
{
	confirmSafeToWriteToMap();
	PropertyMap& aSection = sSectionsMap.vals()[kVarsSectionIdx];
	DBG_ASSERT(theVarID >= 0 && theVarID < aSection.size());
	Property& aVarProp = aSection.vals()[theVarID];
	if( !aVarProp.file.empty() )
	{
		// Need to send a copy of .file, not a reference to it, since .file
		// will be cleared during the function before the reference is used!
		const std::string anOldVal = aVarProp.file;
		setPropertyAfterLoad(kVarsSectionIdx, theVarID, anOldVal, false);
	}
}


void setNewStr(
	const std::string& theSection,
	const std::string& thePropertyName,
	const std::string& theValue)
{
	if( getStr(theSection, thePropertyName) == "" )
		setStr(theSection, thePropertyName, theValue);
}


const SectionsMap& changedSections()
{
	return sChangedSectionsMap;
}


void clearChangedSections()
{
	sChangedSectionsMap.clear();
}


void saveChangesToFile()
{
	if( sUnsavedChangesList.empty() || sLoadedProfileIdx == 0 )
		return;
	const std::string& aFilePath =
		sProfiles.vals()[sLoadedProfileIdx].path;
	for(int i = 0, end = intSize(sUnsavedChangesList.size()); i < end; ++i)
	{
		const std::string& aSectionName =
			sSectionsMap.keys()[sUnsavedChangesList[i].sectionID];
		const PropertyMap& aPropMap =
			sSectionsMap.vals()[sUnsavedChangesList[i].sectionID];
		const std::string& aPropName =
			aPropMap.keys()[sUnsavedChangesList[i].propertyID];
		const std::string& aPropValue = sUnsavedChangesList[i].value;

		setPropertyInINI(aFilePath, aSectionName, aPropName, aPropValue);
	}
	sUnsavedChangesList.clear();
}

} // Profile
